const allPosts = [
    { category: 'it', path: 'it - full-stack web developer', title: 'Full-stack web developer', description: 'Các công nghệ mà tôi sử dụng', date: '2020-02-18 22:47:00' },
    { category: 'it', path: 'it - virtualbox', title: 'Phần mềm VirtualBox', description: 'Tạo máy ảo', date: '2020-02-19 22:40:00' },
    { category: 'it', path: 'it - web development roadmap', title: 'Web development roadmap', description: 'From zero to deployment', date: '2020-02-18 22:48:00' },
    { category: 'js', path: 'js - common', title: 'CommonUtils', description: 'Các hàm dùng chung hay dùng', date: '2020-04-16 22:36:00' },
    { category: 'js', path: 'js - contact picker api', title: 'Contact Picker API', description: 'Chọn từ danh bạ', date: '2020-02-11 21:30:00' },
    { category: 'js', path: 'js - file saver', title: 'Save and load text file by JS', description: 'save, download, load', date: '2020-02-24 22:05:00' },
    { category: 'js', path: 'js - qr code', title: 'QR code', description: 'Generator, scanner, quick', date: '2020-02-12 22:00:00' },
    { category: 'laravel', path: 'laravel - authentication', title: 'Xác thực với Laravel', description: 'Đăng ký, đăng nhập, đăng xuất, quên mật khẩu', date: '2020-02-23 21:50:00' },
    { category: 'laravel', path: 'laravel - installation', title: 'Cài đặt Laravel', description: 'Khởi tạo dự án mới', date: '2020-02-23 21:31:00' },
    { category: 'linux', path: 'linux - install glusterfs', title: 'Cài đặt GlusterFS', description: 'GlusterFS', date: '2020-02-23 01:01:01' },
    { category: 'linux', path: 'linux - install mysql', title: 'Cài đặt MySQL trên Ubuntu', description: 'Cài đặt MySQL trên Ubuntu', date: '2020-02-21 22:56:00' },
    { category: 'linux', path: 'linux - install nginx', title: 'Cài đặt nginx trên Ubuntu', description: 'linux, nginx, ubuntu, selinux', date: '2020-02-20 21:53:00' },
    { category: 'linux', path: 'linux - install node', title: 'Cài đặt Node', description: 'nvm', date: '2020-02-21 19:02:00' },
    { category: 'linux', path: 'linux - install php', title: 'Cài đặt PHP trên Ubuntu', description: 'php8', date: '2020-02-19 23:54:00' },
    { category: 'linux', path: 'linux - install ubuntu server', title: 'Cài đặt Ubuntu Server', description: 'Ubuntu Server, VirtualBox', date: '2020-02-19 23:15:00' },
    { category: 'linux', path: 'linux - linux mint version history', title: 'Các phiên bản Linux Mint', description: 'Phiên bản Ubuntu tương ứng', date: '2020-04-05 16:10:00' },
    { category: 'linux', path: 'linux - run php with nginx', title: 'Chạy PHP với nginx', description: 'php-fpm', date: '2020-02-20 22:24:00' },
    { category: 'linux', path: 'linux - setup lab environment', title: 'Thiết lập môi trường lab', description: 'Thiết lập môi trường lab', date: '2020-02-19 22:41:00' },
    { category: 'linux', path: 'linux - ssh', title: 'Sử dụng SSH', description: 'passwordless', date: '2020-02-19 23:27:00' },
    { category: 'project', path: 'project - common validation', title: 'Common validation', description: 'Validate thời gian thực', date: '2020-02-24 22:07:00' },
    { category: 'project', path: 'project - datatable', title: 'Datatable', description: 'sort, search, pagination, bootstrap, table, fixed header, fixed column', date: '2020-02-24 22:35:00' },
    { category: 'project', path: 'project - frontend frameworks and libraries', title: 'Các framework và thư viện frontend hay dùng', description: 'cdn, zip', date: '2020-02-24 18:28:00' },
    { category: 'project', path: 'project - noti', title: 'Noti', description: 'Thay thế alert và confirm', date: '2020-02-24 22:06:00' },
    { category: 'project', path: 'project - pagi', title: 'Pagi', description: 'A pagination library written by myself', date: '2020-04-16 18:21:00' },
    { category: 'project', path: 'project - post management', title: 'Quản lý bài viết', description: 'Quản lý các bài viết trên blog của tôi', date: '2020-01-01 15:56:00' },
    { category: 'redis', path: 'redis - installation', title: 'Cài đặt Redis', description: 'Cài đặt Redis', date: '2020-02-21 23:20:00' },
    { category: 'ui', path: 'ui - carousel', title: 'Carousel', description: 'carousel, water margin, thủy hử, 108 vị anh hùng Lương Sơn Bạc, 108 heroes', date: '2020-06-22 21:15:00' }
];

const allArchive = [
    { category: 'bootstrap', path: 'bootstrap - badge', title: 'Bootstrap badge', description: 'Bootstrap badge' },
    { category: 'bootstrap', path: 'bootstrap - card', title: 'Bootstrap card', description: 'Bootstrap card' },
    { category: 'bootstrap', path: 'bootstrap - collapse', title: 'Bootstrap collapse', description: 'toggle animation' },
    { category: 'bootstrap', path: 'bootstrap - color', title: 'Màu sắc trong Bootstrap', description: 'Màu sắc trong Bootstrap' },
    { category: 'bootstrap', path: 'bootstrap - compile with koala', title: 'Biên dịch Bootstrap với Koala', description: 'Biên dịch Bootstrap với Koala' },
    { category: 'bootstrap', path: 'bootstrap - customize theme', title: 'Chỉnh sửa lại theme của Bootstrap', description: 'bootstrap, customize, theme' },
    { category: 'bootstrap', path: 'bootstrap - dropdown', title: 'Bootstrap dropdown', description: 'notification, menu đa cấp (multilevel)' },
    { category: 'bootstrap', path: 'bootstrap - flex', title: 'Bootstrap 4 Flex', description: 'Bootstrap 4 Flex' },
    { category: 'bootstrap', path: 'bootstrap - form', title: 'Hướng dẫn thiết kế form với Bootstrap', description: 'input, textarea, select, checkbox, radio, toggle switch, file input, range, button' },
    { category: 'bootstrap', path: 'bootstrap - get started', title: 'Bootstrap', description: 'Bootstrap' },
    { category: 'bootstrap', path: 'bootstrap - media', title: 'Bootstrap Media', description: 'Bootstrap Media tutorial' },
    { category: 'bootstrap', path: 'bootstrap - modal', title: 'Bootstrap modal', description: 'popup' },
    { category: 'bootstrap', path: 'bootstrap - navbar', title: 'Bootstrap Navbar', description: 'Bootstrap Navbar' },
    { category: 'bootstrap', path: 'bootstrap - pagination', title: 'Phân trang trong Bootstrap', description: 'Phân trang trong Bootstrap' },
    { category: 'bootstrap', path: 'bootstrap - popover', title: 'Popover', description: 'Popover' },
    { category: 'bootstrap', path: 'bootstrap - progress bar', title: 'Bootstrap Example', description: 'Bootstrap Example' },
    { category: 'bootstrap', path: 'bootstrap - same height columns', title: 'Các cột có cùng chiều cao', description: 'flex, h-100' },
    { category: 'bootstrap', path: 'bootstrap - spinner', title: 'Bootstrap spinner', description: 'processing, loading' },
    { category: 'bootstrap', path: 'bootstrap - tooltip', title: 'Bootstrap Tooltip', description: 'Bootstrap Tooltip' },
    { category: 'bootstrap', path: 'bootstrap - typography', title: 'Bootstrap typography', description: 'Bootstrap typography' },
    { category: 'bootstrap', path: 'bootstrap - utilities', title: 'Các class tiện ích Bootstrap', description: 'border, sizing, overflow, float, spacing' },
    { category: 'bootstrap', path: 'bootstrap - version 5', title: 'Bootstrap 5', description: 'Version 5' },
    { category: 'composer', path: 'composer - basic usage', title: 'Sử dụng Composer', description: 'Sử dụng Composer' },
    { category: 'composer', path: 'composer - folder structure', title: 'Cấu trúc thư mục của dự án dùng Composer', description: 'psr-4, autoload' },
    { category: 'composer', path: 'composer - installation', title: 'Cài đặt Composer', description: 'linux, composer, windows' },
    { category: 'composer', path: 'composer - locking', title: 'Locking trong Composer', description: 'lock' },
    { category: 'composer', path: 'composer - override vendor classes', title: 'Ghi đè file thư viện PHP với Composer', description: 'php' },
    { category: 'composer', path: 'composer - package version', title: 'Chỉ định version cho các package trong Composer', description: 'composer version' },
    { category: 'composer', path: 'composer - proxy', title: 'Cấu hình proxy cho Composer', description: 'Composer proxy' },
    { category: 'composer', path: 'composer - publish packagist', title: 'Đưa thư viện lưu trên Packagist', description: 'packagist' },
    { category: 'composer', path: 'composer - require-dev', title: 'Composer require-dev', description: 'Các package chỉ phục vụ lúc phát triển' },
    { category: 'css', path: 'css - animation', title: 'CSS animation', description: 'animate.css, slide in, anagram, reveal animations when scrolling, wow.js, pulse, box-shadow, zoom, grow, hover effect' },
    { category: 'css', path: 'css - arrows', title: 'CSS Arrows', description: 'CSS Arrows' },
    { category: 'css', path: 'css - aspect ratio', title: 'Maintain Aspect Ratio', description: 'Maintain Aspect Ratio' },
    { category: 'css', path: 'css - backdrop-filter', title: 'Backdrop-filter', description: 'Backdrop-filter' },
    { category: 'css', path: 'css - background', title: '', description: '' },
    { category: 'css', path: 'css - blend-mode', title: '', description: '' },
    { category: 'css', path: 'css - box-shadow', title: 'CSS box-shadow', description: 'CSS box-shadow' },
    { category: 'css', path: 'css - change autofill style', title: 'Đổi style cho trường mà trình duyệt tự điền dữ liệu', description: '-webkit-autofill' },
    { category: 'css', path: 'css - circular progress bar', title: '', description: '' },
    { category: 'css', path: 'css - clip-path', title: 'Thuộc tính clip-path', description: 'Tạo các shape đơn giản, shape-outside' },
    { category: 'css', path: 'css - column', title: 'CSS column', description: 'CSS column' },
    { category: 'css', path: 'css - critical css', title: 'Critical CSS', description: 'Tách inline các CSS sử dụng' },
    { category: 'css', path: 'css - css for print', title: '', description: '' },
    { category: 'css', path: 'css - css selector', title: 'CSS Selector', description: 'Sử dụng ở cả CSS và JS để chọn phần tử' },
    { category: 'css', path: 'css - filters', title: 'CSS Filters', description: 'CSS Filters' },
    { category: 'css', path: 'css - first letter selector', title: 'First-letter Selector', description: 'Làm nổi bật chữ đầu tiên của đoạn văn' },
    { category: 'css', path: 'css - flexbox introduction', title: 'Giới thiệu Flexbox', description: 'Giới thiệu Flexbox để xây dựng bố cục trang' },
    { category: 'css', path: 'css - float', title: 'CSS Layout - float and clear', description: 'CSS Layout - float and clear' },
    { category: 'css', path: 'css - font-weight', title: 'CSS font-weight', description: 'CSS font-weight' },
    { category: 'css', path: 'css - grid', title: 'CSS Grid', description: 'CSS Grid' },
    { category: 'css', path: 'css - hide arrows on number input', title: 'Ẩn mũi tên ở thẻ input number', description: 'Ẩn mũi tên ở thẻ input number' },
    { category: 'css', path: 'css - image sprites', title: '', description: '' },
    { category: 'css', path: 'css - less', title: 'LESS - A CSS Pre-processor', description: 'A CSS pre-processor' },
    { category: 'css', path: 'css - mix-blend-mode', title: 'mix-blend-mode', description: 'blend, css, video, background' },
    { category: 'css', path: 'css - multi-level menu', title: '', description: '' },
    { category: 'css', path: 'css - object-fit', title: 'CSS The object-fit Property', description: 'CSS The object-fit Property' },
    { category: 'css', path: 'css - perspective', title: 'CSS Perspective', description: 'CSS Perspective' },
    { category: 'css', path: 'css - placeholder-shown', title: 'CSS selector :placeholder-shown', description: 'CSS selector :placeholder-shown' },
    { category: 'css', path: 'css - position', title: '', description: '' },
    { category: 'css', path: 'css - position sticky', title: 'Position sticky', description: 'Position sticky' },
    { category: 'css', path: 'css - precedence', title: '', description: '' },
    { category: 'css', path: 'css - sass', title: 'Sass', description: 'Sửa dụng Sass để tổ chức CSS' },
    { category: 'css', path: 'css - shapes', title: 'CSS Shapes', description: 'CSS Shapes' },
    { category: 'css', path: 'css - text stroke', title: 'Text stroke', description: 'Viền của chữ' },
    { category: 'css', path: 'css - text-overflow', title: 'Hiển thị dấu ba chấm khi text quá dài', description: 'text-overflow, line-clamp' },
    { category: 'css', path: 'css - text-shadow', title: 'Cool Text Effects Using CSS Text-Shadow', description: 'Cool Text Effects Using CSS Text-Shadow' },
    { category: 'css', path: 'css - vertical align', title: 'Vertical Align Examples', description: 'Vertical Align Examples' },
    { category: 'css', path: 'css - web font', title: 'Demo Roboto', description: '' },
    { category: 'css', path: 'css - word wrap', title: '', description: '' },
    { category: 'deno', path: 'deno - aqua web framework', title: 'Aqua web framework', description: 'Một framework đơn giản, code rất ít' },
    { category: 'deno', path: 'deno - deno book', title: 'Lập trình với Deno', description: 'Sách' },
    { category: 'deno', path: 'deno - get started', title: 'Học Deno', description: 'Học Deno' },
    { category: 'deno', path: 'deno - installation', title: 'Cài đặt Deno', description: 'offline, manually' },
    { category: 'docker', path: 'docker - get started', title: 'Docker Get Started', description: 'Docker Get Started' },
    { category: 'docker', path: 'docker - laravel container', title: 'Tạo Docker container cho ứng dụng Laravel', description: 'Tạo Docker container cho ứng dụng Laravel' },
    { category: 'elasticsearch', path: 'elasticsearch - get started', title: 'Elasticsearch Get started', description: 'Elasticsearch Get started' },
    { category: 'git', path: 'git - beginner\'s guide for dummies', title: 'Git Beginner\'s Guide for dummies', description: 'Git Beginner\'s Guide for dummies' },
    { category: 'git', path: 'git - book cover', title: 'Book cover', description: 'Book cover' },
    { category: 'git', path: 'git - branch', title: 'Kỹ thuật phân nhánh (Branching) trong Git', description: 'git' },
    { category: 'git', path: 'git - cheatsheet', title: 'Git cheatsheet', description: 'Git' },
    { category: 'git', path: 'git - commit and staging area', title: 'Tìm hiểu về Commit và Staging Area trong Git', description: 'Git' },
    { category: 'git', path: 'git - compare revisions', title: 'Compare Revisions', description: 'Compare Revisions' },
    { category: 'git', path: 'git - disable crlf warning', title: 'Tắt cảnh báo CRLF', description: 'Disable CRLF warning' },
    { category: 'git', path: 'git - external merge and diff tools', title: 'External Merge and Diff Tools', description: 'External Merge and Diff Tools' },
    { category: 'git', path: 'git - git and github', title: 'git và Github là gì? Tại sao nên dùng?', description: 'git' },
    { category: 'git', path: 'git - git flow', title: 'Quy trình phân nhánh branch chuẩn', description: 'git flow' },
    { category: 'git', path: 'git - git-chain', title: 'git-chain', description: 'git-chain' },
    { category: 'git', path: 'git - github repo size', title: 'GitHub Repo Size', description: 'GitHub Repo Size' },
    { category: 'git', path: 'git - gitignore', title: '.gitignore', description: '.gitignore' },
    { category: 'git', path: 'git - history of a file', title: 'Xem lịch sử thay đổi của một file', description: 'gitk' },
    { category: 'git', path: 'git - init repository', title: 'Cách tạo repository trong Git và Github', description: 'Git' },
    { category: 'git', path: 'git - install and config', title: 'Cài đặt git và thiết lập ban đầu', description: 'git' },
    { category: 'git', path: 'git - introduction', title: 'Giới thiệu serie git cơ bản', description: 'git' },
    { category: 'git', path: 'git - learning', title: 'Git', description: 'Git' },
    { category: 'git', path: 'git - log and undo', title: 'Git log', description: 'Git log' },
    { category: 'git', path: 'git - proxy', title: 'Sử dụng proxy trong git', description: 'git proxy' },
    { category: 'git', path: 'git - remote repository and origin', title: 'Git - Sơ lược Remote Repository và Git', description: 'Git' },
    { category: 'git', path: 'git - remove files', title: 'Remove Files', description: 'Remove Files' },
    { category: 'git', path: 'git - repository server', title: 'Cách tự tạo Repository cho Git trên Server riêng', description: 'Git' },
    { category: 'git', path: 'git - revert modified files', title: 'Loại bỏ các file đã thay đổi', description: 'Git' },
    { category: 'git', path: 'git - save git password', title: 'Lưu mật khẩu git', description: 'Save git password so you don\'t have to keep typing it when you pull/push something' },
    { category: 'git', path: 'git - tag', title: 'Đánh tag với git', description: 'Hướng dẫn tag (đánh dấu)' },
    { category: 'git', path: 'git - use ssh key', title: 'Use SSH key with git', description: 'Use SSH key with git' },
    { category: 'highcharts', path: 'highcharts - examples', title: 'Các ví dụ Highcharts', description: 'demo' },
    { category: 'highcharts', path: 'highcharts - learning', title: 'Tìm hiểu Highcharts', description: 'Tìm hiểu Highcharts' },
    { category: 'highcharts', path: 'highcharts - network graph', title: 'Highcharts network graph', description: 'Mind map' },
    { category: 'highmaps', path: 'highmaps - map bubble', title: 'Bản đồ thế giới', description: 'Map bubble, REST Countries API, Hiển thị thông tin các nước trên thế giới' },
    { category: 'highmaps', path: 'highmaps - vietnamese', title: 'Bản đồ Việt Nam', description: 'Bản đồ Việt Nam' },
    { category: 'it', path: 'it - buy pc', title: 'Buy a new PC', description: 'Guideline to buy a new PC' },
    { category: 'it', path: 'it - check application alive', title: 'Check Application Alive', description: 'Check Application Alive' },
    { category: 'it', path: 'it - check file type', title: 'Kiểm tra định dạng file', description: 'extension, mime' },
    { category: 'it', path: 'it - config web https', title: 'Cấu hình HTTPS cho ứng dụng web', description: 'Cấu hình HTTPS cho ứng dụng web' },
    { category: 'it', path: 'it - convert html to epub', title: 'Convert HTML to EPUB', description: 'Convert HTML to EPUB' },
    { category: 'it', path: 'it - cryptography', title: 'Cryptography', description: 'Cryptography' },
    { category: 'it', path: 'it - curl', title: 'Câu lệnh curl', description: 'Câu lệnh curl' },
    { category: 'it', path: 'it - datetime', title: 'Kiểu dữ liệu datetime trong lập trình', description: 'datetime' },
    { category: 'it', path: 'it - epub format', title: 'Cấu trúc file epub', description: 'Cấu trúc file epub' },
    { category: 'it', path: 'it - facebook api', title: 'Facebook', description: '' },
    { category: 'it', path: 'it - facebook app', title: 'Tạo Facebook app', description: 'Tạo Facebook app' },
    { category: 'it', path: 'it - ffmpeg', title: '', description: '' },
    { category: 'it', path: 'it - filefilter', title: 'File filter', description: 'upcode, deploy' },
    { category: 'it', path: 'it - install os and softwares', title: 'Cài đặt hệ điều hành và phần mềm', description: 'Install OS and softwares' },
    { category: 'it', path: 'it - install wemp stack', title: 'Cài đặt WEMP stack', description: 'windows, nginx, mariadb, php' },
    { category: 'it', path: 'it - it companies in vietnam', title: 'IT Companies', description: 'IT Companies' },
    { category: 'it', path: 'it - link target blank', title: 'Lỗi ATTT link target="_blank"', description: 'security' },
    { category: 'it', path: 'it - link to iframe', title: '', description: '' },
    { category: 'it', path: 'it - lunar calendar', title: 'Tính toán âm lịch', description: 'vietnamese calendar' },
    { category: 'it', path: 'it - multimedia analyzer with ffprobe', title: 'Lấy thông tin file đa phương tiện với ffprobe', description: 'Lấy thông tin file đa phương tiện với ffprobe' },
    { category: 'it', path: 'it - mutable and immutable', title: 'Mutable và immutable', description: 'Mutable và immutable' },
    { category: 'it', path: 'it - ngrok', title: 'Tool ngrok', description: 'Mang demo dự án web lên internet không cần deploy' },
    { category: 'it', path: 'it - oracle ddl query', title: '', description: '' },
    { category: 'it', path: 'it - pass-by-reference and pass-by-value', title: 'Pass-by-reference và pass-by-value', description: 'pass-by-reference, pass-by-value' },
    { category: 'it', path: 'it - personal website', title: 'Trang web cá nhân', description: 'GitHub Page' },
    { category: 'it', path: 'it - picture tag', title: 'Thẻ picture', description: 'Responsive src của ảnh' },
    { category: 'it', path: 'it - regular expression', title: 'Biểu thức chính quy', description: 'regex nói chung, không phân biệt ngôn ngữ lập trình' },
    { category: 'it', path: 'it - run chrome in application mode', title: 'Mở web ở chế độ app', description: 'shortcut' },
    { category: 'it', path: 'it - simple web server', title: 'Web server đơn giản', description: 'Simple web server' },
    { category: 'it', path: 'it - single sign-on', title: 'Single Sign-on', description: 'sso, cookie, session, login' },
    { category: 'it', path: 'it - social login', title: '', description: '' },
    { category: 'it', path: 'it - social share', title: 'Social Share', description: 'Thêm link chia sẻ qua Facebook, Google+, Twitter, LinkedIn, Pinterest, Email' },
    { category: 'it', path: 'it - sql database conventions', title: 'Thiết kế CSDL', description: 'Database conventions' },
    { category: 'it', path: 'it - sql tuning', title: '', description: '' },
    { category: 'it', path: 'it - unit test', title: 'Unit test', description: 'Unit test' },
    { category: 'it', path: 'it - using svg', title: 'Sử dụng SVG', description: 'icon, map' },
    { category: 'it', path: 'it - video streaming', title: 'Video streaming', description: 'm3u8, ts, ffmpeg, nginx, rtmp, rtsp, camera' },
    { category: 'it', path: 'it - visual studio code', title: 'Công cụ soạn thảo Visual Studio Code', description: 'VSCode' },
    { category: 'it', path: 'it - web contenteditable', title: 'Chỉnh sửa trực tiếp với contenteditable', description: 'Inline editing with contenteditable' },
    { category: 'it', path: 'it - web load balancer', title: 'Load balancer', description: 'Cân bằng tải' },
    { category: 'it', path: 'it - web security checklist', title: 'Checklist ATTT cho ứng dụng web', description: 'web security' },
    { category: 'it', path: 'it - webvtt', title: 'Text track', description: 'subtitle' },
    { category: 'java', path: 'java - apache common demo', title: '', description: '' },
    { category: 'java', path: 'java - apk to jar', title: 'apk to jar', description: 'apk to jar' },
    { category: 'java', path: 'java - compress', title: 'Compress', description: 'Compress' },
    { category: 'java', path: 'java - core java http server', title: 'HTTP Server bằng Java thuần', description: 'socket' },
    { category: 'java', path: 'java - crawler', title: 'Crawler với Java', description: 'Crawl các domain bằng Google theo từ khóa' },
    { category: 'java', path: 'java - datetime', title: '', description: '' },
    { category: 'java', path: 'java - db structure', title: '', description: '' },
    { category: 'java', path: 'java - drm', title: '', description: '' },
    { category: 'java', path: 'java - flying-saucer demo', title: 'Flying Saucer', description: 'Flying Saucer' },
    { category: 'java', path: 'java - install eclipse', title: 'Cài đặt IDE Eclipse', description: 'Cài đặt IDE Eclipse' },
    { category: 'java', path: 'java - java-demo', title: '', description: '' },
    { category: 'java', path: 'java - jodconverter demo', title: 'JODConverter', description: 'JODConverter' },
    { category: 'java', path: 'java - jsoup', title: 'Jsoup', description: 'Jsoup' },
    { category: 'java', path: 'java - log alert', title: 'Log Alert', description: 'Cảnh báo khi có log lỗi' },
    { category: 'java', path: 'java - maven', title: 'Bắt đầu với Maven', description: 'eclipse' },
    { category: 'java', path: 'java - pdf doc', title: 'PDF & DOC', description: 'PDF & DOC' },
    { category: 'js', path: 'js - ajax', title: 'AJAX', description: 'XMLHttpRequest vs Fetch API vs jQuery AJAX vs axios' },
    { category: 'js', path: 'js - array', title: 'Mảng trong JS', description: 'Mảng trong JS' },
    { category: 'js', path: 'js - arrow function', title: 'Arrow function', description: 'Arrow function' },
    { category: 'js', path: 'js - asynchronous', title: 'Thực hiện hàm không đồng bộ', description: 'callback, promise, async, await' },
    { category: 'js', path: 'js - audio and microphone visualizer', title: 'Audio and Microphone Visualizer', description: 'Audio and Microphone Visualizer' },
    { category: 'js', path: 'js - axios with cancellation', title: 'axios with cancellation', description: 'axios with cancellation' },
    { category: 'js', path: 'js - binary data', title: 'Binary Data', description: 'Binary Data' },
    { category: 'js', path: 'js - blob', title: 'Using Blob', description: 'Using Blob' },
    { category: 'js', path: 'js - bookmarklet', title: 'Bookmarklet', description: 'Bookmarklet' },
    { category: 'js', path: 'js - breadth first search algorithm', title: '', description: '' },
    { category: 'js', path: 'js - breaking a return statement', title: 'Breaking a return statement', description: 'Breaking a return statement' },
    { category: 'js', path: 'js - browser console', title: 'Browser console', description: 'Browser console' },
    { category: 'js', path: 'js - calculating week number', title: 'Calculating week numbers in JS', description: 'Calculating week numbers in JS' },
    { category: 'js', path: 'js - canvas', title: 'JS Canvas', description: 'JS Canvas' },
    { category: 'js', path: 'js - ckeditor', title: 'CKEditor', description: 'CKEditor' },
    { category: 'js', path: 'js - clipboard', title: 'Clipboard', description: 'Xử lý khi paste' },
    { category: 'js', path: 'js - closure', title: 'JS Closure', description: 'closure, let, variable scope' },
    { category: 'js', path: 'js - concatenating audio files with web audio api', title: 'Nối nhiều file audio vào làm một', description: 'Nối nhiều file audio vào làm một' },
    { category: 'js', path: 'js - const and let', title: 'Khai báo với const và let', description: 'Khai báo với const và let' },
    { category: 'js', path: 'js - cookie', title: 'Cookie', description: 'Cookie' },
    { category: 'js', path: 'js - copy text', title: 'Copy text', description: 'Copy text' },
    { category: 'js', path: 'js - custom event', title: 'Custom Event', description: 'Custom Event' },
    { category: 'js', path: 'js - default parameter', title: 'Default parameter', description: 'Default parameter' },
    { category: 'js', path: 'js - design patterns', title: 'Design patterns', description: 'Design patterns' },
    { category: 'js', path: 'js - destructuring assignment', title: 'Destructuring Assignment', description: 'Destructuring Assignment' },
    { category: 'js', path: 'js - dijkstra algorithm', title: '', description: '' },
    { category: 'js', path: 'js - dom to canvas animation', title: 'DOM to Canvas animation', description: 'HTML to Canvas animation' },
    { category: 'js', path: 'js - drag and drop', title: 'Kéo thả trên web', description: 'drag and drop, jquery ui sortable' },
    { category: 'js', path: 'js - embed youtube video', title: 'Nhúng video vào trang web', description: 'YouTube, Facebook' },
    { category: 'js', path: 'js - epub reader', title: 'EPUB Reader', description: 'EPUB Reader' },
    { category: 'js', path: 'js - epub viewer (bibi)', title: 'EPUB Reader', description: 'EPUB Reader' },
    { category: 'js', path: 'js - es6', title: 'JS - ES6', description: 'Các tính năng mới và hay trong JS' },
    { category: 'js', path: 'js - eslint', title: 'Sử dụng ESLint', description: 'lint, vscode' },
    { category: 'js', path: 'js - event delegation', title: 'Event Delegation', description: 'matches, closet' },
    { category: 'js', path: 'js - events', title: 'JS event', description: 'JS event' },
    { category: 'js', path: 'js - excel', title: 'Export và import file Excel với JS', description: 'Export và import file Excel với JS' },
    { category: 'js', path: 'js - exception', title: '', description: '' },
    { category: 'js', path: 'js - execcommand', title: 'document.execCommand', description: 'WYSIWYG editor' },
    { category: 'js', path: 'js - export docx', title: 'Xuất file docx với JS', description: 'word document' },
    { category: 'js', path: 'js - facebook comment', title: 'Thêm Facebook comment vào trang', description: 'Thêm Facebook comment vào trang' },
    { category: 'js', path: 'js - fake webcam', title: 'Display Webcam Stream', description: 'Display Webcam Stream' },
    { category: 'js', path: 'js - file api', title: '', description: '' },
    { category: 'js', path: 'js - full text search', title: 'JS full text search', description: 'lunr, fuse' },
    { category: 'js', path: 'js - fullpage.js', title: '', description: '' },
    { category: 'js', path: 'js - fullpage.js with animate.css', title: 'fullPage.js with animate.css', description: 'fullPage.js with animate.css' },
    { category: 'js', path: 'js - fullpage.js with wow.js', title: 'Wow.js Animate.css text animation', description: 'Wow.js Animate.css text animation' },
    { category: 'js', path: 'js - fullscreen', title: 'Full-screen API', description: 'Chế độ toàn màn hình' },
    { category: 'js', path: 'js - function', title: 'JS function', description: 'JS function' },
    { category: 'js', path: 'js - functional programming', title: 'JS functional programming', description: 'JS functional programming' },
    { category: 'js', path: 'js - generator', title: 'JS generator', description: 'JS generator' },
    { category: 'js', path: 'js - geolocation', title: 'Geolocation', description: 'Geolocation' },
    { category: 'js', path: 'js - get computed css', title: 'Get Computed CSS', description: 'Get computed CSS' },
    { category: 'js', path: 'js - get parameter', title: 'Lấy giá trị tham số từ URL bằng JS', description: 'Lấy giá trị tham số từ URL bằng JS' },
    { category: 'js', path: 'js - getset', title: 'Getter, setter trong JS', description: 'getter, setter, getset' },
    { category: 'js', path: 'js - giojs', title: 'Gio.js', description: '3D globe, map' },
    { category: 'js', path: 'js - google drive api', title: 'Google Drive API', description: 'upload file, create folder' },
    { category: 'js', path: 'js - google map', title: '', description: '' },
    { category: 'js', path: 'js - google sheet api', title: 'Google Sheet API', description: 'Google Sheet API' },
    { category: 'js', path: 'js - google translate api', title: 'Sử dụng Google Translate API', description: 'Dịch tiếng Anh sang tiếng Việt' },
    { category: 'js', path: 'js - gulp', title: 'Bắt đầu với Gulp', description: 'Bắt đầu với Gulp' },
    { category: 'js', path: 'js - highlightjs', title: 'Highlight source code syntax', description: 'highlight.js' },
    { category: 'js', path: 'js - history api', title: 'History API', description: 'history' },
    { category: 'js', path: 'js - html sanitizer', title: 'HTML sanitizer', description: 'HTML sanitizer' },
    { category: 'js', path: 'js - image loader', title: 'Image Loader', description: 'css, js, image loader' },
    { category: 'js', path: 'js - image processing (marvinj)', title: 'Marvinj', description: 'Xử lý ảnh' },
    { category: 'js', path: 'js - infinite scroll', title: 'Infinite scroll', description: 'Load tiếp bản ghi khi kéo xuống cuối trang' },
    { category: 'js', path: 'js - insertadjacenthtml', title: 'insertAdjacentHTML', description: 'insertAdjacentHTML' },
    { category: 'js', path: 'js - jest (unit test)', title: 'Unit test với Jest', description: 'Unit test với Jest', date: '2020-02-27 10:22:00' },
    { category: 'js', path: 'js - jquery-comments', title: 'jQuery comment', description: 'Một thư viện về comment rất hay' },
    { category: 'js', path: 'js - js in 2016', title: 'JS năm 2016', description: 'Bức tranh toàn cảnh JS năm 2016' },
    { category: 'js', path: 'js - json form binding', title: '', description: '' },
    { category: 'js', path: 'js - key event', title: 'Bắt sự kiện nhập từ bàn phím', description: 'Key event' },
    { category: 'js', path: 'js - key sequence detection', title: 'Key Sequence Detection', description: 'keyboard' },
    { category: 'js', path: 'js - keyboard input', title: 'Keyboard input handler', description: 'Keyboard input handler' },
    { category: 'js', path: 'js - live reload', title: 'Live Reload', description: 'Live Reload' },
    { category: 'js', path: 'js - load file async and defer', title: 'Load file JS async và defer', description: 'Load file JS async và defer' },
    { category: 'js', path: 'js - masked input', title: 'Masked Input', description: 'Masked Input' },
    { category: 'js', path: 'js - mergely diff demo', title: 'Mergely diff demo', description: 'Mergely diff demo' },
    { category: 'js', path: 'js - midi player', title: 'MIDIjs', description: 'MIDIjs' },
    { category: 'js', path: 'js - mobile number', title: '', description: '' },
    { category: 'js', path: 'js - module', title: 'Module', description: 'module.exports, exports - require (Node), export - import (ES6)' },
    { category: 'js', path: 'js - monitering dom changes', title: 'Monitoring DOM changes', description: 'Monitoring DOM changes' },
    { category: 'js', path: 'js - multi-language', title: '', description: '' },
    { category: 'js', path: 'js - my own repeat template', title: '', description: '' },
    { category: 'js', path: 'js - notification api', title: 'Notification API', description: 'Thông báo hệ thống' },
    { category: 'js', path: 'js - nullish coalescing', title: 'Nullish coalescing', description: 'Hợp nhất null, falsy, truthy' },
    { category: 'js', path: 'js - obfuscate code', title: 'Làm rối code JS', description: 'Làm rối code JS' },
    { category: 'js', path: 'js - object literal', title: 'Object literal', description: 'Khai báo đối tượng' },
    { category: 'js', path: 'js - onbeforeunload', title: '', description: '' },
    { category: 'js', path: 'js - onmousedown', title: '', description: '' },
    { category: 'js', path: 'js - oop', title: 'Lập trình hướng đối tượng trong JS', description: 'class, object oriented programming' },
    { category: 'js', path: 'js - optional chaining', title: 'Optional chaining', description: 'Optional chaining' },
    { category: 'js', path: 'js - output pretty json', title: 'Output pretty JSON', description: 'Output pretty JSON' },
    { category: 'js', path: 'js - page scroll', title: 'Page scroll', description: 'Page scroll' },
    { category: 'js', path: 'js - page visibility api', title: '', description: '' },
    { category: 'js', path: 'js - paginate text', title: 'Paginate Text', description: 'Paginate Text' },
    { category: 'js', path: 'js - parseint', title: '', description: '' },
    { category: 'js', path: 'js - perfect scrollbar', title: 'Perfect Scrollbar', description: 'perfect-scrollbar' },
    { category: 'js', path: 'js - picture in picture', title: 'Picture-in-Picture', description: 'Picture-in-Picture Web API' },
    { category: 'js', path: 'js - playing an mp3 file with web audio api', title: 'Playing an MP3 file with the Web Audio API', description: 'Playing an MP3 file with the Web Audio API' },
    { category: 'js', path: 'js - prevent copy content', title: 'Không cho phép copy content từ web', description: 'Không cho phép copy content từ web' },
    { category: 'js', path: 'js - private field', title: 'Private field', description: 'Private field trong class' },
    { category: 'js', path: 'js - proxy', title: 'Proxy trong JS', description: 'proxy' },
    { category: 'js', path: 'js - pure pubsub', title: 'Pure JS PubSub System', description: 'Pure JS PubSub System' },
    { category: 'js', path: 'js - push api', title: 'Push API', description: 'Push API' },
    { category: 'js', path: 'js - pwa', title: 'Bắt đầu với PWA', description: 'pwa, Progressive Web App' },
    { category: 'js', path: 'js - refer to parent from iframe', title: '', description: '' },
    { category: 'js', path: 'js - regular expression', title: 'Biểu thức chính quy trong JS', description: 'regex' },
    { category: 'js', path: 'js - relative mouse coordinate', title: 'Get relative mouse coordinate', description: 'Get relative mouse coordinate' },
    { category: 'js', path: 'js - replace function', title: 'Phương thức String replace trong JS', description: 'str.replace()' },
    { category: 'js', path: 'js - requestanimationframe', title: 'requestAnimationFrame', description: 'requestAnimationFrame' },
    { category: 'js', path: 'js - rest parameters', title: 'Rest Parameter', description: 'Rest Parameter' },
    { category: 'js', path: 'js - right click context menu', title: 'Right click context menu', description: 'Right click context menu' },
    { category: 'js', path: 'js - riot', title: 'Riot', description: 'Riot' },
    { category: 'js', path: 'js - say numbers', title: '', description: '' },
    { category: 'js', path: 'js - screen size', title: 'Lấy kích thước màn hình', description: 'dimension' },
    { category: 'js', path: 'js - simple multi-language translation', title: 'Simple Multi-language translation', description: 'Simple Multi-language translation' },
    { category: 'js', path: 'js - slide up down', title: 'Slide up and down', description: 'Slide up and down' },
    { category: 'js', path: 'js - sort vietnamese', title: 'Sắp xếp tiếng Việt', description: 'Sắp xếp tiếng Việt' },
    { category: 'js', path: 'js - spatial navigation', title: '', description: '' },
    { category: 'js', path: 'js - speech recognition', title: 'Nhận dạng tiếng nói', description: 'speech recognition, voice input, asr' },
    { category: 'js', path: 'js - spread operator', title: 'Spread Operator', description: 'Spread Operator' },
    { category: 'js', path: 'js - spread syntax', title: 'JS Spread syntax', description: 'JS Spread syntax' },
    { category: 'js', path: 'js - storage quota', title: 'Storage API', description: 'IndexedDB' },
    { category: 'js', path: 'js - string methods', title: 'Các phương thức của String trong JS', description: 'Các phương thức của String trong JS' },
    { category: 'js', path: 'js - string to arraybuffer', title: 'Convert String to ArrayBuffer', description: 'Convert String to ArrayBuffer' },
    { category: 'js', path: 'js - summernote', title: 'Summernote', description: 'A simple editor' },
    { category: 'js', path: 'js - symbol', title: 'Symbol trong JS', description: 'Symbol' },
    { category: 'js', path: 'js - template string', title: 'Template string', description: 'Template string' },
    { category: 'js', path: 'js - text to speech', title: 'Tổng hợp tiếng nói', description: 'Text to speech, speech synthesis' },
    { category: 'js', path: 'js - toc', title: 'Tự sinh mục lục', description: 'Table of content' },
    { category: 'js', path: 'js - typescript', title: '', description: '' },
    { category: 'js', path: 'js - upload image preview', title: 'Preview file ảnh', description: 'Upload image preview' },
    { category: 'js', path: 'js - upload multiple files', title: 'Upload nhiều file', description: 'Cho phép chọn nhiều file, từng file một. Có thể bỏ bớt file. Submit sau đó cùng các thông tin khác.' },
    { category: 'js', path: 'js - vara', title: 'Vara.js', description: 'Simulate signature animation' },
    { category: 'js', path: 'js - vietkey', title: '', description: '' },
    { category: 'js', path: 'js - wavesurfer', title: 'Wavesurfer', description: 'Wavesurfer' },
    { category: 'js', path: 'js - web socket', title: 'Web Socket', description: 'Web Socket client, chat' },
    { category: 'js', path: 'js - window open function', title: '', description: '' },
    { category: 'js', path: 'js - zip', title: 'Nén và giải nén ZIP file', description: 'zip' },
    { category: 'laravel', path: 'laravel - artisan', title: 'Laravel Artisan', description: 'Thực hiện các lệnh PHP artisan' },
    { category: 'laravel', path: 'laravel - authorization', title: 'Phân quyền trong Laravel', description: 'Laravel authorization' },
    { category: 'laravel', path: 'laravel - blade template', title: 'Blade template', description: 'Blade template' },
    { category: 'laravel', path: 'laravel - broadcasting with pusher', title: 'Laravel Pusher', description: 'Laravel Pusher' },
    { category: 'laravel', path: 'laravel - cache', title: 'Xử lý cache trong Laravel', description: 'Xử lý cache trong Laravel' },
    { category: 'laravel', path: 'laravel - cheat sheet', title: 'Laravel Cheat Sheet', description: 'Laravel Cheat Sheet' },
    { category: 'laravel', path: 'laravel - configuration', title: 'Cấu hình Laravel', description: 'env' },
    { category: 'laravel', path: 'laravel - contract', title: 'Laravel Contract', description: 'Laravel Contract' },
    { category: 'laravel', path: 'laravel - controller', title: 'Laravel Controller', description: 'Laravel Controller' },
    { category: 'laravel', path: 'laravel - cookie', title: 'Laravel Cookie', description: 'Laravel Cookie' },
    { category: 'laravel', path: 'laravel - create helper functions', title: 'Tạo hàm dùng chung', description: 'Tạo hàm dùng chung' },
    { category: 'laravel', path: 'laravel - csrf', title: 'Phòng chống lỗi ATTT CSRF', description: 'Phòng chống lỗi ATTT CSRF' },
    { category: 'laravel', path: 'laravel - custom webpack configuration', title: 'Laravel Custom Webpack Configuration', description: 'Laravel Custom Webpack Configuration' },
    { category: 'laravel', path: 'laravel - database', title: 'Laravel Database', description: 'Laravel Database' },
    { category: 'laravel', path: 'laravel - deploy', title: 'Triển khai ứng dụng Laravel', description: 'No application encryption key has been specified' },
    { category: 'laravel', path: 'laravel - eloquent', title: 'Laravel Eloquent', description: 'Laravel Eloquent' },
    { category: 'laravel', path: 'laravel - eloquent collections', title: 'Laravel Eloquent Collections', description: 'Laravel Eloquent Collections' },
    { category: 'laravel', path: 'laravel - eloquent fill method', title: 'Laravel Eloquent fill method', description: 'Laravel Eloquent fill method' },
    { category: 'laravel', path: 'laravel - eloquent mutators', title: 'Laravel Eloquent Mutators', description: 'Laravel Eloquent Mutators' },
    { category: 'laravel', path: 'laravel - eloquent relationships', title: 'Laravel Eloquent Relationships', description: 'Laravel Eloquent Relationships' },
    { category: 'laravel', path: 'laravel - eloquent serialization', title: 'Laravel Eloquent Serialization', description: 'Laravel Eloquent Serialization' },
    { category: 'laravel', path: 'laravel - email verification', title: 'Laravel Email Verification', description: 'Laravel Email Verification' },
    { category: 'laravel', path: 'laravel - encryption', title: 'Laravel Encryption', description: 'Mã hóa, cryptography' },
    { category: 'laravel', path: 'laravel - error', title: 'Laravel Error', description: 'Laravel Error' },
    { category: 'laravel', path: 'laravel - events', title: 'Laravel Events', description: 'Laravel Events' },
    { category: 'laravel', path: 'laravel - excel', title: 'Laravel Excel', description: 'Laravel Excel, import, export' },
    { category: 'laravel', path: 'laravel - facade', title: 'Laravel Facade', description: 'Laravel Facade' },
    { category: 'laravel', path: 'laravel - file upload', title: 'Upload file với Laravel', description: 'Upload file với Laravel' },
    { category: 'laravel', path: 'laravel - filesystem', title: 'Laravel Filesystem', description: 'Quản lý file (upload) với Laravel' },
    { category: 'laravel', path: 'laravel - folder structure', title: 'Laravel Folder Structure', description: 'Laravel Folder Structure' },
    { category: 'laravel', path: 'laravel - frontend', title: 'Laravel frontend', description: 'Laravel frontend' },
    { category: 'laravel', path: 'laravel - get sql string', title: 'Lấy câu SQL', description: 'Lấy câu SQL' },
    { category: 'laravel', path: 'laravel - get started', title: 'Bắt đầu học Laravel', description: 'Bắt đầu học Laravel' },
    { category: 'laravel', path: 'laravel - hashing', title: 'Laravel Hashing', description: 'Laravel Hashing' },
    { category: 'laravel', path: 'laravel - helpers', title: 'Các hàm helper', description: 'Các hàm helper' },
    { category: 'laravel', path: 'laravel - i18n', title: 'Laravel i18n', description: 'Laravel i18n' },
    { category: 'laravel', path: 'laravel - jwt', title: 'JWT (JSON Web Token) trong Laravel', description: 'jwt, laravel' },
    { category: 'laravel', path: 'laravel - khoa pham course', title: 'Laravel Khoa Pham Videos', description: 'Laravel Khoa Pham Videos' },
    { category: 'laravel', path: 'laravel - logging', title: 'Quản lý log trong Laravel', description: 'logging' },
    { category: 'laravel', path: 'laravel - mail', title: 'Gửi mail với Laravel', description: 'Laravel mail' },
    { category: 'laravel', path: 'laravel - maintainace mode', title: 'Chế độ bảo trì', description: 'upgrade, update' },
    { category: 'laravel', path: 'laravel - middleware', title: 'Laravel Middleware', description: 'Laravel Middleware' },
    { category: 'laravel', path: 'laravel - migrations', title: 'Laravel Migrations', description: 'Laravel Migrations' },
    { category: 'laravel', path: 'laravel - mix', title: 'Laravel Mix', description: 'Compile, minimize file CSS, JS' },
    { category: 'laravel', path: 'laravel - models folder', title: 'Thêm thư mục Models trong Laravel', description: 'Thêm thư mục Models trong Laravel' },
    { category: 'laravel', path: 'laravel - notification', title: 'Laravel Database Notification', description: 'Laravel Database Notification' },
    { category: 'laravel', path: 'laravel - oauth 2 with passport', title: 'Xác thực OAuth 2 với Laravel', description: 'Xác thực OAuth 2 với Laravel' },
    { category: 'laravel', path: 'laravel - pagination', title: 'Phân trang trong Laravel', description: 'Laravel Pagination' },
    { category: 'laravel', path: 'laravel - query builder', title: 'Laravel Query Builder', description: 'Laravel Query Builder' },
    { category: 'laravel', path: 'laravel - queue', title: 'Hàng đợi trong Laravel', description: 'Xử lý công việc kiểu background, hàng đợi với Laravel' },
    { category: 'laravel', path: 'laravel - rate limit', title: 'Giới hạn truy cập với Laravel', description: 'Laravel Rate Limit' },
    { category: 'laravel', path: 'laravel - redis', title: 'Laravel Redis', description: 'Laravel Redis' },
    { category: 'laravel', path: 'laravel - request', title: 'Laravel Request', description: 'Laravel Request' },
    { category: 'laravel', path: 'laravel - reset password', title: 'Reset mật khẩu với Laravel', description: 'Thực hiện chức năng quên mật khẩu trong Laravel' },
    { category: 'laravel', path: 'laravel - response', title: 'Laravel Response', description: 'Laravel Response' },
    { category: 'laravel', path: 'laravel - route, url, asset', title: 'Laravel route, url, asset', description: 'Laravel route, url, asset' },
    { category: 'laravel', path: 'laravel - routing', title: 'Laravel Routing', description: 'Laravel Routing' },
    { category: 'laravel', path: 'laravel - scheduling', title: 'Laravel Scheduling', description: 'Thực hiện các tiến trình đặt lịch với Laravel' },
    { category: 'laravel', path: 'laravel - scout', title: 'Laravel Scout', description: 'Laravel Scout' },
    { category: 'laravel', path: 'laravel - seeding', title: 'Laravel Seeding', description: 'Thêm dữ liệu vào database' },
    { category: 'laravel', path: 'laravel - service container', title: 'Laravel Service Container', description: 'Laravel Service Container' },
    { category: 'laravel', path: 'laravel - service provider', title: 'Laravel Service Provider', description: 'Laravel Service Provider' },
    { category: 'laravel', path: 'laravel - session', title: 'Quản lý session trong Laravel', description: 'Laravel session' },
    { category: 'laravel', path: 'laravel - sharing data between views', title: 'Sharing data between views', description: 'Sharing data between views' },
    { category: 'laravel', path: 'laravel - socialite', title: 'Laravel Socialite', description: 'Laravel Socialite' },
    { category: 'laravel', path: 'laravel - testing', title: 'Kiểm thử với Laravel', description: 'Kiểm thử với Laravel' },
    { category: 'laravel', path: 'laravel - two-factor authentication', title: 'Xác thực 2 lớp với Laravel', description: 'google authenticator, time-based one-time password, totp, 2fa, mac, hmac' },
    { category: 'laravel', path: 'laravel - upgrading to version 5.7 from 5.6', title: 'Upgrading To 5.7 From 5.6', description: 'Upgrading To 5.7 From 5.6' },
    { category: 'laravel', path: 'laravel - use mysql colllate', title: 'Sử dụng collate của MySQL trong Laravel', description: 'Sử dụng collate của MySQL trong Laravel' },
    { category: 'laravel', path: 'laravel - validation', title: 'Validation trong Laravel', description: 'Laravel validation' },
    { category: 'laravel', path: 'laravel - version 7', title: 'Laravel 7', description: 'Laravel 7 có gì mới' },
    { category: 'laravel', path: 'laravel - view', title: 'Laravel View', description: 'Laravel View' },
    { category: 'laravel', path: 'laravel - view composer', title: 'Laravel View Composer', description: 'Laravel View Composer' },
    { category: 'laravel', path: 'laravel - voyager configuration', title: 'Cấu hình Voyager', description: 'Cấu hình Voyager' },
    { category: 'laravel', path: 'laravel - voyager get started', title: 'Giới thiệu Voyager', description: 'laravel, admin, voyager' },
    { category: 'linux', path: 'linux - apt command', title: 'Hướng dẫn sử dụng lệnh apt', description: 'Hướng dẫn sử dụng lệnh apt' },
    { category: 'linux', path: 'linux - crontab', title: 'Crontab', description: 'Crontab' },
    { category: 'linux', path: 'linux - customize computer style', title: '', description: '' },
    { category: 'linux', path: 'linux - disable ipv6', title: 'Disable IPv6', description: 'Disable IPv6' },
    { category: 'linux', path: 'linux - force copy', title: 'Force cp to overwrite without confirmation', description: 'Force cp to overwrite without confirmation' },
    { category: 'linux', path: 'linux - install lemp stack on centos', title: 'Cài đặt LEMP stack trên CentOS', description: 'centos, nginx, mariadb, php, redis' },
    { category: 'linux', path: 'linux - install oracle jdk', title: 'Cài đặt OracleJDK trên Linux', description: 'OpenJDK, OracleJDK, jdk' },
    { category: 'linux', path: 'linux - install vietnamese input method on ubuntu', title: 'Hướng dẫn cài bộ gõ tiếng Việt trên Ubuntu', description: 'ibus-unikey' },
    { category: 'linux', path: 'linux - keep app alive', title: 'Giữ tiến trình luôn chạy', description: 'Giữ tiến trình luôn chạy trên Linux' },
    { category: 'linux', path: 'linux - mount', title: 'Mount ổ cứng', description: 'Mount ổ cứng' },
    { category: 'linux', path: 'linux - permission', title: 'Phân quyền trong Linux', description: 'selinux, umask' },
    { category: 'linux', path: 'linux - resize, convert and modify images', title: 'Chỉnh sửa ảnh', description: 'resize, convert, modify, image processing, imagemagick' },
    { category: 'linux', path: 'linux - rsync command', title: 'Lệnh rsync', description: 'Đồng bộ file giữa hai server, sync' },
    { category: 'linux', path: 'linux - service management', title: 'Quản lý service', description: 'Service management' },
    { category: 'linux', path: 'linux - setting path', title: 'Cấu hình path trên Linux', description: 'Setting path' },
    { category: 'linux', path: 'linux - ssh port forwarding', title: 'SSH port forward', description: 'ssh tunnel' },
    { category: 'linux', path: 'linux - sudo', title: 'The Differences between su, sudo su, sudo -s and sudo -i', description: 'The Differences between su, sudo su, sudo -s and sudo -i' },
    { category: 'linux', path: 'linux - user and group', title: 'User và group trong Linux', description: 'permission' },
    { category: 'linux', path: 'linux - vi editor', title: 'Hướng dẫn sử dụng vi', description: 'Hướng dẫn sử dụng vi' },
    { category: 'linux', path: 'linux - vietnamese input method', title: 'Nhập tiếng Việt trong vim', description: 'Nhập tiếng Việt trong vim' },
    { category: 'linux', path: 'linux - view folder tree', title: 'Hiển thị cây thư mục', description: 'ls, directory' },
    { category: 'mysql', path: 'mysql - character set and collation', title: 'Character Set và Collation trong MySQL', description: 'Tìm kiếm, so sánh, sắp xếp tiếng Việt, không phân biệt hoa thường' },
    { category: 'mysql', path: 'mysql - common table exrepssion (cte)', title: 'Common Table Expression (CTE)', description: 'Common Table Expression (CTE)' },
    { category: 'mysql', path: 'mysql - create a new user and grant permissions', title: 'Tạo mới người dùng và gán quyền trong', description: 'How to create a new user and grant permissions in MySQL' },
    { category: 'mysql', path: 'mysql - data types', title: 'Các kiểu dữ liệu trong MySQL', description: 'mysql' },
    { category: 'mysql', path: 'mysql - explain', title: 'Phân tích câu lệnh MySQL với explain', description: 'Phân tích câu lệnh MySQL với explain' },
    { category: 'mysql', path: 'mysql - full text search', title: 'Full text search trong MySQL', description: 'MySQL Full text search' },
    { category: 'mysql', path: 'mysql - get started', title: 'Học MySQL', description: 'Học MySQL' },
    { category: 'mysql', path: 'mysql - import and export', title: 'Import và export MySQL', description: 'mysql, import, export' },
    { category: 'mysql', path: 'mysql - index', title: 'Sử dụng index trong MySQL', description: 'Sử' },
    { category: 'mysql', path: 'mysql - json data type', title: 'Kiểu dữ liệu JSON', description: 'json, mariadb' },
    { category: 'mysql', path: 'mysql - store binary file', title: 'Lưu file (ảnh) dạng binary trong MySQL', description: 'Lưu file (ảnh) dạng binary trong MySQL' },
    { category: 'mysql', path: 'mysql - type date', title: '', description: '' },
    { category: 'mysql', path: 'mysql - window function', title: 'Window function', description: 'Window function' },
    { category: 'nginx', path: 'nginx - autoindex', title: 'Liệt kê thư mục', description: 'Liệt kê thư mục' },
    { category: 'nginx', path: 'nginx - block', title: 'Block với nginx', description: 'Block với nginx' },
    { category: 'nginx', path: 'nginx - change run user', title: 'Thay đổi user chạy Nginx Server và PHP-FPM', description: 'Thay đổi user chạy Nginx Server và PHP-FPM' },
    { category: 'nginx', path: 'nginx - configuration', title: 'Cấu hình nginx', description: 'Cấu hình nginx' },
    { category: 'nginx', path: 'nginx - get started', title: 'Tìm hiểu nginx', description: 'Tìm hiểu nginx' },
    { category: 'nginx', path: 'nginx - load balancer', title: 'Nginx Load Balancer', description: 'Nginx Load Balancer' },
    { category: 'nginx', path: 'nginx - location configuration', title: 'Cấu hình location trong nginx', description: 'Cấu hình location trong nginx' },
    { category: 'nginx', path: 'nginx - reverse proxy', title: 'Nginx Reverse Proxy', description: 'Nginx Reverse Proxy' },
    { category: 'node', path: 'node - bundle single executable', title: '', description: '' },
    { category: 'node', path: 'node - electron', title: 'Electron', description: 'electron, node, npm proxy' },
    { category: 'node', path: 'node - get started', title: 'Học Node', description: 'Học Node' },
    { category: 'node', path: 'node - npm proxy', title: 'Cấu hình proxy cho npm', description: 'Configure proxy to install Node package' },
    { category: 'node', path: 'node - publish package', title: 'Publish một package lên npm', description: 'Publish một package lên npm' },
    { category: 'node', path: 'node - puppeteer', title: 'Hướng dẫn puppeteer', description: 'Demo crawl ArtStation' },
    { category: 'php', path: 'php - apache virtual host', title: 'Cấu hình Virtual host trong Apache', description: 'Cấu hình Virtual host trong Apache' },
    { category: 'php', path: 'php - array', title: 'Mảng trong PHP', description: 'Mảng trong PHP' },
    { category: 'php', path: 'php - async event driven (websocket) workerman', title: '', description: '' },
    { category: 'php', path: 'php - autoload', title: 'Autoload trong PHP', description: 'Autoload trong PHP' },
    { category: 'php', path: 'php - block request on windows', title: 'Block request PHP trên Windows', description: 'php-fpm, FastCGI, CGI, PHP_FCGI_CHILDREN' },
    { category: 'php', path: 'php - boolean', title: 'Các giá trị, hàm boolean trong PHP', description: 'falsy, isset, empty, Elvis operator, Null-coalescing operator' },
    { category: 'php', path: 'php - callback function', title: 'Hàm callback trong PHP', description: 'Hàm callback trong PHP' },
    { category: 'php', path: 'php - character encoding', title: '', description: '' },
    { category: 'php', path: 'php - check upload file extension', title: 'Kiểm tra định dạng file upload', description: 'Laravel' },
    { category: 'php', path: 'php - closure', title: 'PHP Closure', description: 'PHP Closure' },
    { category: 'php', path: 'php - compact function', title: 'Hàm compact', description: 'Hàm compact' },
    { category: 'php', path: 'php - config upload', title: 'Cấu hình upload size cho PHP', description: 'upload, 413 Request Entity Too Large' },
    { category: 'php', path: 'php - constant', title: 'Hằng số trong PHP', description: 'Hằng số trong PHP' },
    { category: 'php', path: 'php - curl', title: 'cURL', description: 'download' },
    { category: 'php', path: 'php - datetime', title: '', description: '' },
    { category: 'php', path: 'php - debug', title: 'Debug code PHP', description: 'Debug code PHP' },
    { category: 'php', path: 'php - dompdf', title: '', description: '' },
    { category: 'php', path: 'php - excel', title: 'Thao tác file Excel với PHP', description: 'Thao tác file Excel với PHP' },
    { category: 'php', path: 'php - excel error', title: 'Lỗi xuất báo cáo Excel với PHP', description: 'Lỗi xuất báo cáo Excel với PHP' },
    { category: 'php', path: 'php - exception', title: 'Xử lý Exception trong PHP', description: 'Xử lý Exception trong PHP' },
    { category: 'php', path: 'php - execute external command', title: 'Thực hiện các lệnh hệ thống với PHP', description: 'exec, system, rar, 7z' },
    { category: 'php', path: 'php - execute from cli', title: 'PHP CLI', description: 'PHP CLI' },
    { category: 'php', path: 'php - extension', title: 'PHP extension', description: 'phpize' },
    { category: 'php', path: 'php - faker', title: 'Tạo dữ liệu với Faker', description: 'Tạo dữ liệu với Faker' },
    { category: 'php', path: 'php - file', title: 'Xử lý dữ liệu trên file trong PHP', description: 'read, write' },
    { category: 'php', path: 'php - get started', title: 'Lập trình PHP', description: 'PHP Get Started' },
    { category: 'php', path: 'php - guzzle', title: 'Sử dụng Guzzle để gọi API', description: 'PHP Guzzle' },
    { category: 'php', path: 'php - heredoc and nowdoc', title: 'Heredoc và nowdoc', description: 'Heredoc và nowdoc' },
    { category: 'php', path: 'php - html parser', title: 'HTML Parser', description: 'DOMDocument, purify, sanitize' },
    { category: 'php', path: 'php - html purifier', title: 'HTML purifier', description: 'sanitize, xss' },
    { category: 'php', path: 'php - ixudra curl', title: '', description: '' },
    { category: 'php', path: 'php - json', title: 'Xử lý JSON trong PHP', description: 'Xử lý JSON trong PHP' },
    { category: 'php', path: 'php - ldap', title: 'Đăng nhập LDAP với PHP', description: 'ldap, php, laravel' },
    { category: 'php', path: 'php - merge images', title: '', description: '' },
    { category: 'php', path: 'php - mock api', title: 'Mock API', description: 'Giả lập dữ liệu từ server, REST, socket server' },
    { category: 'php', path: 'php - mvc', title: 'Cài đặt ứng dụng PHP thuần sử dụng MVC và OOP', description: 'Cài đặt ứng dụng PHP thuần sử dụng MVC và OOP' },
    { category: 'php', path: 'php - mysql', title: 'Truy cập MySQL với PHP', description: 'pdo, mysqli' },
    { category: 'php', path: 'php - new features php8', title: 'Những cái mới trong PHP 8', description: 'php8' },
    { category: 'php', path: 'php - oop', title: 'Lập trình hướng đối tượng với PHP', description: 'Lập trình hướng đối tượng với PHP' },
    { category: 'php', path: 'php - os', title: 'Kiểm tra loại hệ điều hành', description: 'Kiểm tra loại hệ điều hành' },
    { category: 'php', path: 'php - password hash', title: '', description: '' },
    { category: 'php', path: 'php - phar file format', title: 'PHAR file format', description: 'PHAR file format' },
    { category: 'php', path: 'php - phpexcel', title: 'Sử dụng PHPExcel', description: 'Sử dụng PHPExcel' },
    { category: 'php', path: 'php - phpmailer', title: '', description: '' },
    { category: 'php', path: 'php - phpunit', title: 'PHP Unit Test', description: 'PHP Unit Test' },
    { category: 'php', path: 'php - psr', title: 'Các chuẩn PHP khuyên dùng', description: 'PSR' },
    { category: 'php', path: 'php - pure php and mix', title: 'Sử dụng PHP thuần với Laravel Mix', description: 'Không sử dụng Laravel' },
    { category: 'php', path: 'php - raw http request', title: 'Tạo raw HTTP request', description: 'socket' },
    { category: 'php', path: 'php - read mail', title: 'Đọc mail với PHP', description: 'imap, pop3' },
    { category: 'php', path: 'php - regular expression', title: 'Biểu thức chính quy trong PHP', description: 'regex, preg_match' },
    { category: 'php', path: 'php - rename', title: 'Rename', description: 'Đổi tên file hàng loạt, check special characters' },
    { category: 'php', path: 'php - route', title: 'Cách tạo router - routing - PHP', description: 'Cách tạo router - routing - PHP' },
    { category: 'php', path: 'php - soap client', title: '', description: '' },
    { category: 'php', path: 'php - sprintf function', title: '', description: '' },
    { category: 'php', path: 'php - sqlite', title: 'Sử dụng SQLite với PHP', description: 'sqlite' },
    { category: 'php', path: 'php - string functions', title: 'Các hàm xử lý xâu trong PHP', description: 'Các hàm xử lý xâu trong PHP' },
    { category: 'php', path: 'php - swiftmailer', title: '', description: '' },
    { category: 'php', path: 'php - template engine', title: 'Cách tạo template engine kế thừa trong PHP', description: 'Cách tạo template engine kế thừa trong PHP' },
    { category: 'php', path: 'php - top 100 functions', title: 'Top 100 hàm PHP', description: 'Top 100 hàm PHP' },
    { category: 'php', path: 'php - trait', title: 'Trait trong php', description: 'Trait trong php' },
    { category: 'php', path: 'php - variable', title: 'Biến trong PHP', description: 'Biến trong PHP' },
    { category: 'php', path: 'php - variable reference', title: '', description: '' },
    { category: 'php', path: 'php - watermark', title: 'PHP watermark', description: 'PHP watermark' },
    { category: 'php', path: 'php - zip', title: 'Thao tác với ZIP file bằng PHP', description: 'zip, rar, extract, compress, docx' },
    { category: 'project', path: 'project - aff cup 2018', title: 'AFF 2018 Thailand', description: 'AFF 2018 Thailand' },
    { category: 'project', path: 'project - audio book', title: 'Audio truyện', description: 'playlist, Tam quốc diễn nghĩa' },
    { category: 'project', path: 'project - calculator', title: 'JS Calculator', description: 'JS Calculator' },
    { category: 'project', path: 'project - change wallpaper', title: 'Tự động đổi wallpaper', description: 'node, pkg' },
    { category: 'project', path: 'project - classmates', title: 'Lớp Toán khóa 2002-2005 trường THPT Chuyên Hưng Yên', description: 'Lớp Toán khóa 2002-2005 trường THPT Chuyên Hưng Yên' },
    { category: 'project', path: 'project - clean html', title: 'Clean HTML', description: 'Chỉ giữ những thẻ cần thiết nhất' },
    { category: 'project', path: 'project - comic reader', title: 'Comic Reader', description: 'Comic reader' },
    { category: 'project', path: 'project - comic reader (full page)', title: 'Comic Reader - Full Page', description: 'Comic Reader - Full Page' },
    { category: 'project', path: 'project - comic reader (half page)', title: 'Half page', description: 'comic reader, xem ảnh trên mobile' },
    { category: 'project', path: 'project - comic reader (strip)', title: 'Old Master Q', description: 'Chú Thoòng' },
    { category: 'project', path: 'project - comic reader cbz cbr', title: 'Comic Reader', description: 'Đọc file cbz, cbr' },
    { category: 'project', path: 'project - comic split', title: 'Split ảnh truyện tranh', description: 'Split ảnh truyện tranh' },
    { category: 'project', path: 'project - comics manager', title: 'Comics Manager', description: 'Comics Manager' },
    { category: 'project', path: 'project - cttd', title: 'CTTD', description: 'CTTD' },
    { category: 'project', path: 'project - diff', title: '', description: '' },
    { category: 'project', path: 'project - disable open new ad tab', title: '', description: '' },
    { category: 'project', path: 'project - doc truyen', title: 'Đọc truyện đêm khuya', description: 'Đọc truyện đêm khuya' },
    { category: 'project', path: 'project - download github folder', title: 'DownGit', description: 'Download GitHub folder, zip' },
    { category: 'project', path: 'project - english common words', title: 'Những từ tiếng Anh thông dụng', description: 'Học tiếng Anh với hình ảnh và âm thanh' },
    { category: 'project', path: 'project - fast read (spritz-speed-reading-v2)', title: 'Spritz Speed Reading V2', description: 'Spritz Speed Reading V2' },
    { category: 'project', path: 'project - fast read 1', title: 'Đọc nhanh', description: 'Đọc nhanh từng từ của một đoạn văn bản' },
    { category: 'project', path: 'project - format css', title: 'Format CSS', description: 'Format CSS' },
    { category: 'project', path: 'project - get links', title: 'Get links', description: 'Lấy các link (ảnh, video) để download. Lấy nội dung, thông tin của ảnh.' },
    { category: 'project', path: 'project - homepage', title: 'Trang chủ', description: 'motorbike oil alert, calendar, water, electricity, bill warning' },
    { category: 'project', path: 'project - lich cua toi', title: 'Lịch của tôi', description: 'lunar calendar, Progressive Web App, pwa, lichcuatoi.github.io, offline, service worker' },
    { category: 'project', path: 'project - lien hoan hoa', title: '', description: '' },
    { category: 'project', path: 'project - manga rock image decoder', title: '', description: '' },
    { category: 'project', path: 'project - map', title: 'View Position', description: 'View Position' },
    { category: 'project', path: 'project - markdown preview', title: 'Markdown preview', description: 'Markdown preview' },
    { category: 'project', path: 'project - mdm', title: '', description: '' },
    { category: 'project', path: 'project - media player', title: 'Media player', description: 'audio, video, subtitle, karaoke' },
    { category: 'project', path: 'project - media player wayou selected', title: '精選', description: 'a collection of songs that I love, also shows how to sync lyric with HTML5 audio tag' },
    { category: 'project', path: 'project - money manager', title: 'Money Manager', description: 'Money Manager' },
    { category: 'project', path: 'project - movie api', title: '', description: '' },
    { category: 'project', path: 'project - my family', title: 'My Family', description: 'genealogy, tree' },
    { category: 'project', path: 'project - my notes', title: '', description: '' },
    { category: 'project', path: 'project - page viewer', title: 'Page viewer', description: 'Đọc từng trang' },
    { category: 'project', path: 'project - puzzle', title: 'Puzzle', description: 'A puzzle game' },
    { category: 'project', path: 'project - realtime corona', title: '', description: '' },
    { category: 'project', path: 'project - sherlock holmes', title: 'Sherlock Holmes collection', description: 'Sherlock Holmes collection' },
    { category: 'project', path: 'project - short', title: 'Short funny stories', description: 'Short stories' },
    { category: 'project', path: 'project - subtitle', title: 'Đồng bộ lại phụ đề', description: 'Chỉnh lại thời gian của phụ đề cho khớp, Java' },
    { category: 'project', path: 'project - truyen co tich', title: 'Playlist audio truyện cổ tích', description: 'Playlist audio truyện cổ tích' },
    { category: 'project', path: 'project - tts audio book', title: 'Đọc truyện audio bằng tổng hợp tiếng nói', description: 'tts, guzzle, php' },
    { category: 'project', path: 'project - upload file', title: 'Upload file', description: 'Upload từ iPad sang máy tính, download từ máy tính sang iPad' },
    { category: 'project', path: 'project - video playlist', title: 'Playlist video truyện cổ tích Việt Nam', description: 'Playlist video cổ tích Việt Nam' },
    { category: 'project', path: 'project - vietnamese divisions', title: 'Đơn vị hành chính', description: 'Dữ liệu tỉnh, huyện, xã của Việt Nam' },
    { category: 'project', path: 'project - vong quay may man', title: 'Vòng quay may mắn', description: 'Vòng quay may mắn' },
    { category: 'project', path: 'project - weather app', title: 'Dự báo thời tiết', description: '' },
    { category: 'project', path: 'project - world cup 2018', title: 'World Cup 2018', description: 'World Cup 2018' },
    { category: 'python', path: 'python - get started', title: '', description: '' },
    { category: 'react', path: 'react - create react app', title: 'Create React App', description: 'Tool tạo ứng dụng React' },
    { category: 'react', path: 'react - get started', title: 'Học React', description: 'Học React' },
    { category: 'react', path: 'react - hooks', title: 'React hook', description: 'React hook' },
    { category: 'react', path: 'react - redux', title: 'Redux', description: 'Redux' },
    { category: 'react', path: 'react - redux saga', title: 'Redux saga', description: 'Redux saga' },
    { category: 'react', path: 'react - router', title: 'React router', description: 'React router' },
    { category: 'react', path: 'react - tic-tac-toe game', title: 'React tic-tac-toe', description: 'Ví dụ bắt đầu' },
    { category: 'react', path: 'react - without jsx', title: 'React Slider w/ Hover Effect', description: 'React without JSX' },
    { category: 'redis', path: 'redis - get started', title: 'Redis', description: 'Redis' },
    { category: 'story', path: 'story - 10 years of youtube', title: '10 years of Youtube', description: '10 years of Youtube' },
    { category: 'story', path: 'story - all kills of dragon ball characters', title: 'Các nhân vật trong truyện Dragon Ball đã giết bao nhiêu người', description: 'Các nhân vật trong truyện Dragon Ball đã giết bao nhiêu người' },
    { category: 'story', path: 'story - barca', title: 'Màn ngược dòng không tưởng đưa Barca vào tứ kết', description: 'Màn ngược dòng không tưởng đưa Barca vào tứ kết' },
    { category: 'story', path: 'story - chu cho con', title: 'Chú chó con', description: 'A story about a dog' },
    { category: 'story', path: 'story - core values', title: 'Core Values', description: 'Core Values' },
    { category: 'story', path: 'story - dinh van kre, dang van cuong', title: 'Chuyện cổ tích có thật về người thầy hiệu trưởng - “cha nuôi” của cậu bé tí hon 10 tuổi nặng 3,9 kg', description: 'Đặng Văn Cương, Đinh Văn K\'Rể, inspiration' },
    { category: 'story', path: 'story - dont learn english, use it', title: 'Đừng học tiếng Anh, hãy sử dụng', description: 'learn, study, use', date: '2020-01-01 11:50:00' },
    { category: 'story', path: 'story - dresses of different nations', title: 'Dresses of different nations', description: 'Dresses of different nations' },
    { category: 'story', path: 'story - envy', title: 'Ghen tỵ', description: 'Ghen tỵ' },
    { category: 'story', path: 'story - first time in my life', title: 'First time in my life', description: 'The first time' },
    { category: 'story', path: 'story - football and life', title: 'Football', description: 'Football' },
    { category: 'story', path: 'story - height and weight of child', title: 'Bảng chỉ số chiều cao, cân nặng của trẻ', description: 'Bảng chỉ số chiều cao, cân nặng của trẻ' },
    { category: 'story', path: 'story - hinh anh minh hoa sach tap doc xua', title: 'Những hình ảnh minh họa \'bất hủ\' của sách Tập đọc xưa', description: 'Những hình ảnh minh họa \'bất hủ\' của sách Tập đọc xưa' },
    { category: 'story', path: 'story - hoai niem cung nhung mon do co gan lien voi the he 8x', title: 'Hoài niệm cùng những món "đồ cổ" gắn liền với thế hệ 8x', description: 'Hoài niệm cùng những món ' },
    { category: 'story', path: 'story - house construction', title: 'Xây nhà', description: 'House construction' },
    { category: 'story', path: 'story - ideas', title: 'Các ý tưởng của tôi', description: 'My ideas' },
    { category: 'story', path: 'story - it\'s never too late', title: 'It\'s never too late', description: 'It\'s never too late' },
    { category: 'story', path: 'story - journey to the west', title: 'Journey to the West', description: 'Journey to the West' },
    { category: 'story', path: 'story - khong co ten (nguyen thu hang)', title: 'Không có tên', description: 'Truyện ngắn hay về tình mẫu tử của Nguyễn Thu Hằng' },
    { category: 'story', path: 'story - lich tiem chung', title: 'Lịch tiêm chủng', description: 'Lịch tiêm chủng cho con' },
    { category: 'story', path: 'story - life as a sales engineer', title: 'Life as a Sales Engineer', description: 'Life as a Sales Engineer' },
    { category: 'story', path: 'story - my idols', title: 'My Idols', description: 'My Idols' },
    { category: 'story', path: 'story - my plan', title: 'Kế hoạch cho tương lai', description: 'Plan the future' },
    { category: 'story', path: 'story - nutrious food', title: 'Nutritious Food', description: 'Nutritious Food' },
    { category: 'story', path: 'story - personal names', title: '', description: '' },
    { category: 'story', path: 'story - phan biet dinh chua', title: 'Cách phân biệt các điểm du lịch tâm linh', description: 'Phân biệt đình, chùa, miếu, am,...' },
    { category: 'story', path: 'story - q.e.d', title: 'Truyện Q.E.D', description: 'Danh sách tập, vụ án, kiến thức khoa học' },
    { category: 'story', path: 'story - quotes', title: 'Lời hay ý đẹp', description: 'Lời hay ý đẹp' },
    { category: 'story', path: 'story - superior spider-man', title: 'Superior Spider-Man', description: 'Superior Spider-Man' },
    { category: 'story', path: 'story - tax deduction', title: 'Giảm trừ gia cảnh', description: 'Giảm trừ gia cảnh' },
    { category: 'story', path: 'story - tay du ky', title: 'Tây du ký', description: 'Tây du ký' },
    { category: 'story', path: 'story - the story of life', title: 'The Story of Life', description: 'A very good article' },
    { category: 'story', path: 'story - truyen tranh viet nam', title: 'Người nặng lòng với truyện tranh Việt', description: 'Người nặng lòng với truyện tranh Việt' },
    { category: 'story', path: 'story - truyen tranh xua', title: 'Truyện tranh', description: 'Truyện tranh' },
    { category: 'story', path: 'story - washing dish', title: 'Hướng dẫn rửa bát', description: 'Hướng dẫn rửa bát' },
    { category: 'story', path: 'story - websites', title: 'Websites', description: 'Danh sách các trang web hay vào' },
    { category: 'ui', path: 'ui - auto grow', title: 'Auto Grow', description: 'Auto Grow' },
    { category: 'ui', path: 'ui - auto-complete inline', title: 'Auto-complete inline', description: 'Auto-complete inline' },
    { category: 'ui', path: 'ui - book cover', title: 'Book cover', description: 'Book cover' },
    { category: 'ui', path: 'ui - bubble animation', title: 'Bubble Animation', description: 'Bubble Animation' },
    { category: 'ui', path: 'ui - calendar', title: 'Calendar', description: '' },
    { category: 'ui', path: 'ui - card grid', title: 'Card grid', description: 'Pokedex' },
    { category: 'ui', path: 'ui - card grid (alphabet)', title: 'Bảng chữ cái', description: 'Alphabet' },
    { category: 'ui', path: 'ui - change image onhover', title: 'Change Image', description: 'Change Image' },
    { category: 'ui', path: 'ui - character selection', title: 'Street Fighter - Character Selection', description: 'Built by Vue and Bulma' },
    { category: 'ui', path: 'ui - chien tranh bien gioi viet trung', title: 'Chiến tranh biên giới Việt - Trung', description: 'Chiến tranh biên giới Việt - Trung' },
    { category: 'ui', path: 'ui - clearable', title: 'Clearable', description: 'Clear input content' },
    { category: 'ui', path: 'ui - connector', title: 'Step connector', description: 'progress circles' },
    { category: 'ui', path: 'ui - cover board', title: '', description: '' },
    { category: 'ui', path: 'ui - customize scrollbar', title: 'Tùy chỉnh style cho thanh scrollbar', description: 'Tùy chỉnh style cho thanh scrollbar' },
    { category: 'ui', path: 'ui - date range picker', title: 'Date range picker', description: 'Chọn khoảng ngày. Có những khoảng ngày định nghĩa trước cho tiện.' },
    { category: 'ui', path: 'ui - datepicker', title: 'jQuery UI datepicker', description: 'jQuery UI datepicker' },
    { category: 'ui', path: 'ui - datepicker dialog', title: 'Datepicker Dialog', description: 'Cho phép chọn ngày, khoảng ngày, tuần, tháng, mùa, năm' },
    { category: 'ui', path: 'ui - details', title: 'Phần tử details', description: 'details, summary, accordion, collapse, expand, fieldset, legend, heading' },
    { category: 'ui', path: 'ui - diagonal', title: 'Diagonal background', description: 'chéo, transform skew, gradient background, css shape triangle' },
    { category: 'ui', path: 'ui - dock', title: '', description: '' },
    { category: 'ui', path: 'ui - drag position', title: 'Drag position', description: 'Di chuyển vị trí phần tử absolute' },
    { category: 'ui', path: 'ui - dragon ball 42 volumes', title: 'Dragon Ball', description: 'Dragon Ball' },
    { category: 'ui', path: 'ui - dropdown', title: '', description: '' },
    { category: 'ui', path: 'ui - elapsing time', title: 'Elapsing Time', description: 'Elapsing Time' },
    { category: 'ui', path: 'ui - emoticon', title: '', description: '' },
    { category: 'ui', path: 'ui - fit text with css variables', title: 'Fit Text', description: 'Fit Text with CSS Variables' },
    { category: 'ui', path: 'ui - fit to width', title: 'Fit to width', description: 'Fit to width' },
    { category: 'ui', path: 'ui - flame', title: 'Giao diện game', description: 'Có animation, style của game' },
    { category: 'ui', path: 'ui - floating elements', title: 'Floating elements mini snippet', description: 'Floating elements mini snippet' },
    { category: 'ui', path: 'ui - font awesome', title: 'Font Awesome', description: 'Font Awesome' },
    { category: 'ui', path: 'ui - football icons', title: 'Football icons', description: 'Biểu tượng của các đội tuyển quốc gia, các câu lạc bộ' },
    { category: 'ui', path: 'ui - football match', title: 'Football Match', description: 'Football Match' },
    { category: 'ui', path: 'ui - fullscreen video background', title: 'Fullscreen video background', description: 'Fullscreen video background' },
    { category: 'ui', path: 'ui - gallery', title: 'Gallery 1', description: 'A simple gallery' },
    { category: 'ui', path: 'ui - gauge chart', title: 'Biểu đồ Gauge', description: 'Biểu đồ Gauge' },
    { category: 'ui', path: 'ui - generate icon', title: 'Generate Icon', description: 'Generate Icon' },
    { category: 'ui', path: 'ui - globe', title: 'Globe', description: 'Globe' },
    { category: 'ui', path: 'ui - glossy effect', title: '', description: '' },
    { category: 'ui', path: 'ui - gradient', title: 'Gradient', description: 'Gradient' },
    { category: 'ui', path: 'ui - hamburger menu icon', title: 'Hamburger menu icon', description: 'animation đóng mở' },
    { category: 'ui', path: 'ui - hide text too long', title: '', description: '' },
    { category: 'ui', path: 'ui - highlight changes', title: 'Highlight các thay đổi', description: 'Highlight các thay đổi' },
    { category: 'ui', path: 'ui - horizontal scroll', title: 'Horizontal Scroll', description: 'Horizontal Scroll' },
    { category: 'ui', path: 'ui - icon', title: 'Sử dụng icon trên web', description: 'Sử dụng icon trên web' },
    { category: 'ui', path: 'ui - image comparison slider', title: 'So sánh 2 hình ảnh', description: 'So sánh 2 hình ảnh' },
    { category: 'ui', path: 'ui - image fading transition', title: 'Image fading transition', description: 'Image fading transition' },
    { category: 'ui', path: 'ui - image magnifier glass', title: 'Kính lúp', description: 'Image magnifier glass' },
    { category: 'ui', path: 'ui - image map', title: '', description: '' },
    { category: 'ui', path: 'ui - image zoom', title: '', description: '' },
    { category: 'ui', path: 'ui - inline edit', title: 'Inline Edit', description: 'Inline Edit' },
    { category: 'ui', path: 'ui - justice league action', title: 'Justice League Action', description: 'ffmpeg, python subprocess, thumbnail' },
    { category: 'ui', path: 'ui - karaoke', title: 'Karaoke', description: 'Karaoke' },
    { category: 'ui', path: 'ui - ken burns effect', title: 'Ken Burns Effect', description: 'Ken Burns Effect' },
    { category: 'ui', path: 'ui - layout', title: '', description: '' },
    { category: 'ui', path: 'ui - layout bottom footer', title: 'Bottom footer', description: 'Để footer ở cuối trang. Có thể áp dụng để trang hiển thị full chiều cao màn hình.' },
    { category: 'ui', path: 'ui - layout fullscreen', title: 'Full-Screen Layout', description: 'Full-Screen Layout' },
    { category: 'ui', path: 'ui - light loader', title: 'Light Loader', description: 'Light Loader' },
    { category: 'ui', path: 'ui - line awesome', title: 'Line Awesome', description: 'Bộ icon dùng trên web' },
    { category: 'ui', path: 'ui - loader', title: 'Loader', description: 'Loader' },
    { category: 'ui', path: 'ui - lunar new year', title: 'Đếm ngược tết', description: 'Đếm ngược tết' },
    { category: 'ui', path: 'ui - map ammap', title: 'Intro to amMap', description: 'Intro to amMap' },
    { category: 'ui', path: 'ui - map echarts', title: '', description: '' },
    { category: 'ui', path: 'ui - marquee', title: 'Preloader --3', description: 'Preloader --3' },
    { category: 'ui', path: 'ui - masonry', title: 'Masonry', description: 'masonry, column, flex' },
    { category: 'ui', path: 'ui - maxlength indicator', title: 'Bootstrap Maxlength', description: 'Bootstrap Maxlength' },
    { category: 'ui', path: 'ui - menu', title: 'Menu', description: 'Menu' },
    { category: 'ui', path: 'ui - metro card', title: '', description: '' },
    { category: 'ui', path: 'ui - mini preview links', title: 'Mini-Preview link', description: 'Hover trên link sẽ hiển thị popup nhỏ chứa screen của target' },
    { category: 'ui', path: 'ui - month picker', title: 'Chọn tháng', description: 'Month picker' },
    { category: 'ui', path: 'ui - multi layered parallax', title: 'Hiệu ứng parallax nhiều tầng với ảnh và văn bản', description: 'Hiệu ứng parallax nhiều tầng với ảnh và văn bản' },
    { category: 'ui', path: 'ui - neon text-shadow effect', title: 'Neon text-shadow effect', description: 'Neon text-shadow effect' },
    { category: 'ui', path: 'ui - nestable', title: 'Nestable', description: 'Kéo thả danh sách dạng cây, tree' },
    { category: 'ui', path: 'ui - one piece chapters', title: 'One Piece chapters', description: 'One Piece chapters' },
    { category: 'ui', path: 'ui - overlay', title: '', description: '' },
    { category: 'ui', path: 'ui - page split', title: 'Page split', description: 'Tách các thành phần của trang web thành các trang có kích thước cố định' },
    { category: 'ui', path: 'ui - pagemap', title: 'pagemap', description: 'pagemap' },
    { category: 'ui', path: 'ui - paper', title: 'Paper', description: 'Paper' },
    { category: 'ui', path: 'ui - parallax animation', title: 'Hoạt họa parallax', description: 'Animated parallax banner' },
    { category: 'ui', path: 'ui - parallax background', title: 'Parallax background', description: 'Parallax background' },
    { category: 'ui', path: 'ui - parallax elements', title: 'Các thành phần parallax', description: 'Parallax elements, porfolio page' },
    { category: 'ui', path: 'ui - particle animation', title: 'Pure CSS Particle Animation', description: 'Pure CSS Particle Animation' },
    { category: 'ui', path: 'ui - pie chart', title: '', description: '' },
    { category: 'ui', path: 'ui - pin element', title: 'Pin một phần tử', description: 'Pin một phần tử' },
    { category: 'ui', path: 'ui - progress bar', title: '', description: '' },
    { category: 'ui', path: 'ui - radar chart', title: 'Radar chart', description: 'Thống kê chỉ số của các vận động viên' },
    { category: 'ui', path: 'ui - random girl image', title: 'Random girl image', description: 'Hiển thị ngẫu nhiên ảnh một girl xinh' },
    { category: 'ui', path: 'ui - reflection', title: 'Reflection', description: 'Phản chiếu, bóng loáng' },
    { category: 'ui', path: 'ui - refracted floating text effect', title: 'Refracted Floating Text Effect', description: 'Refracted Floating Text Effect' },
    { category: 'ui', path: 'ui - resizable div', title: 'Resizable div', description: 'Resizable div' },
    { category: 'ui', path: 'ui - responsive design', title: 'Responsive Design', description: 'Responsive Design' },
    { category: 'ui', path: 'ui - ribbon', title: 'Ribbon', description: 'Ribbon' },
    { category: 'ui', path: 'ui - row and column highlighting', title: 'Row and Column Highlighting with CSS Only', description: 'Row and Column Highlighting with CSS Only' },
    { category: 'ui', path: 'ui - scroll hover', title: 'Hiện thanh scrollbar khi hover', description: 'Hiện thanh scrollbar khi hover' },
    { category: 'ui', path: 'ui - scrollbar', title: 'Tùy chỉnh scrollbar', description: 'Tùy chỉnh Scrollbar' },
    { category: 'ui', path: 'ui - search box', title: '', description: '' },
    { category: 'ui', path: 'ui - selectable', title: 'Selectable', description: 'Selectable' },
    { category: 'ui', path: 'ui - shapes with css', title: 'The Shapes of CSS', description: 'The Shapes of CSS' },
    { category: 'ui', path: 'ui - shuffle animation', title: 'Shuffle Animation', description: 'Shuffle Animation' },
    { category: 'ui', path: 'ui - sidebar', title: 'Sidebar navigation', description: 'Sidebar navigation' },
    { category: 'ui', path: 'ui - slide show', title: 'Slide show animation', description: 'Wedding photos of Huyên and Dương' },
    { category: 'ui', path: 'ui - sparkle animation', title: 'Sparkle animation', description: 'Heart animation - click it!' },
    { category: 'ui', path: 'ui - speed line', title: '', description: '' },
    { category: 'ui', path: 'ui - split image', title: 'Split image', description: 'Tách một ảnh thành nhiều ảnh nhỏ' },
    { category: 'ui', path: 'ui - split panels resizable', title: 'Dragbar', description: 'Thay đổi kích thước' },
    { category: 'ui', path: 'ui - spoiler', title: '', description: '' },
    { category: 'ui', path: 'ui - spotlight', title: '', description: '' },
    { category: 'ui', path: 'ui - sticky', title: '', description: '' },
    { category: 'ui', path: 'ui - sticky header with intersectionobserver', title: 'Sticky headers with IntersectionObserver', description: 'Sticky headers with IntersectionObserver' },
    { category: 'ui', path: 'ui - sticky sections pure css', title: 'Sticky sections (pure CSS)', description: 'Sticky sections (pure CSS)' },
    { category: 'ui', path: 'ui - sunburst chart', title: 'Sunburst eCharts', description: 'Sunburst eCharts' },
    { category: 'ui', path: 'ui - swipe', title: 'Swipe', description: 'Swipe' },
    { category: 'ui', path: 'ui - tab', title: 'Tab', description: 'Tab' },
    { category: 'ui', path: 'ui - tabs with sliding underline', title: 'Tạo tab với sliding phía dưới', description: 'Tạo tab với sliding phía dưới' },
    { category: 'ui', path: 'ui - text', title: '', description: '' },
    { category: 'ui', path: 'ui - toggle nav when scroll', title: 'Ẩn hiện navigator khi scroll', description: 'Toggle navigator when scrolling' },
    { category: 'ui', path: 'ui - tooltip', title: 'Tooltip', description: 'tooltip' },
    { category: 'ui', path: 'ui - tree diagram', title: '', description: '' },
    { category: 'ui', path: 'ui - tree drawing', title: '', description: '' },
    { category: 'ui', path: 'ui - tree grid', title: 'Tree grid', description: 'Bảng dữ liệu dạng cây' },
    { category: 'ui', path: 'ui - user rating', title: 'User rating', description: 'User rating' },
    { category: 'ui', path: 'ui - wedding photos', title: 'Ảnh cưới của vợ chồng tôi', description: 'lazy load, prefetch, fancybox, lighbox' },
    { category: 'ui', path: 'ui - week picker', title: 'Chọn tuần', description: 'Week picker' },
    { category: 'ui', path: 'ui - word cloud', title: 'Word cloud', description: 'Highcharts, jqcloud2, tag, từ khóa nổi bật' },
    { category: 'vue', path: 'vue - component', title: 'Component trong Vue', description: 'v-model' },
    { category: 'vue', path: 'vue - component custom event', title: 'Custom event trong component', description: 'v-model, sync' },
    { category: 'vue', path: 'vue - component slot', title: 'Slot trong Vue', description: 'slot' },
    { category: 'vue', path: 'vue - form validation', title: 'Vue form validation', description: 'Validate với Vue' },
    { category: 'vue', path: 'vue - fullpage scroll', title: 'Vue Fullpage Scroll', description: 'Vue Fullpage Scroll' },
    { category: 'vue', path: 'vue - get started', title: 'Bắt đầu học Vue', description: 'Bắt đầu học Vue' },
    { category: 'vue', path: 'vue - linkify', title: 'Sử dụng thư viện Linkify với Vue', description: 'Sử dụng thư viện Linkify với Vue' },
    { category: 'vue', path: 'vue - spa', title: 'Tạo SPA với Vue', description: 'Single Page Application' },
    { category: 'vue', path: 'vue - transitions', title: 'Transition cho enter/leave & danh sách', description: '' },
    { category: 'vue', path: 'vue - unit test', title: 'Unit test với Vue', description: 'Unit test với Vue' },
    { category: 'vue', path: 'vue - veevalidate', title: 'VeeValidate', description: 'VeeValidate' },
    { category: 'vue', path: 'vue - vue tags input', title: 'Vue tags input', description: 'Danh sách thẻ' },
    { category: 'webext', path: 'webext - batch downloader', title: 'Batch downloader', description: 'Tiện ích download file hàng loạt' },
    { category: 'webext', path: 'webext - bookmarks api', title: 'Web Extension Bookmarks', description: 'Web Extension Bookmarks' },
    { category: 'webext', path: 'webext - browse my repo', title: 'Browse my repo', description: 'Change URL between my website and GitHub' },
    { category: 'webext', path: 'webext - browser history', title: '', description: '' },
    { category: 'webext', path: 'webext - cloud downloader', title: 'Cloud downloader', description: 'Download từ các trang như usercloud, zippyshare, fshare, mega' },
    { category: 'webext', path: 'webext - coc coc savior', title: 'Cốc Cốc Savior', description: 'Bắt link và download các video, audio' },
    { category: 'webext', path: 'webext - cors unblock', title: 'CORS unblock', description: 'Cho phép gọi AJAX đến domain khác' },
    { category: 'webext', path: 'webext - get source code', title: 'Lấy source code của một extension', description: 'Lấy source code của một extension' },
    { category: 'webext', path: 'webext - get started', title: 'Web Extension', description: 'Web Extension' },
    { category: 'webext', path: 'webext - pin video', title: '', description: '' },
    { category: 'webext', path: 'webext - safenet addon', title: 'Net Filter', description: 'Net Filter' },
    { category: 'webext', path: 'webext - screenshot', title: 'Chụp ảnh màn hình', description: 'Chụp ảnh màn hình để thông báo lỗi, export dữ liệu,... Sử dụng lib html2canvas.' },
    { category: 'webext', path: 'webext - set referer', title: 'Set referer', description: 'Set referer' },
    { category: 'webext', path: 'webext - steal this page', title: '', description: '' },
    { category: 'webext', path: 'webext - sync bookmarks', title: 'Đồng bộ bookmark', description: 'Đẩy dữ liệu bookmark từ máy công ty lên cloud để máy ở nhà cũng xem được' },
    { category: 'webext', path: 'webext - timestats', title: 'timeStats - Time statistics', description: 'timeStats - Time statistics' },
    { category: 'webext', path: 'webext - web cleaner', title: '', description: '' },
    { category: 'webext', path: 'webext - youtube ads remover', title: '', description: '' },
    { category: 'webext', path: 'webext - youtube subtitle downloader', title: 'Tiện ích download subtitle từ YouTube', description: 'youtube, subtitle, download, closed caption' },
    { category: 'webext', path: 'webext - youtube video downloader', title: '', description: '' },
    { category: 'webrtc', path: 'webrtc - file transfer', title: 'Truyền file', description: 'Transfer a file' },
    { category: 'webrtc', path: 'webrtc - get started', title: 'WebRTC', description: 'WebRTC' },
    { category: 'webrtc', path: 'webrtc - simple datachannel', title: 'Channel đơn giản', description: 'WebRTC: Simple RTCDataChannel sample' }
];

