export default [
{"category":"bootstrap","title":"Bootstrap badge","description":"Bootstrap badge","date":null,"path":"bootstrap - badge"},
{"category":"bootstrap","title":"Bootstrap card","description":"Bootstrap card","date":null,"path":"bootstrap - card"},
{"category":"bootstrap","title":"Bootstrap collapse","description":"toggle animation","date":null,"path":"bootstrap - collapse"},
{"category":"bootstrap","title":"Màu sắc trong Bootstrap","description":"Màu sắc trong Bootstrap","date":null,"path":"bootstrap - color"},
{"category":"bootstrap","title":"Biên dịch Bootstrap với Koala","description":"Biên dịch Bootstrap với Koala","date":null,"path":"bootstrap - compile with koala"},
{"category":"bootstrap","title":"Chỉnh sửa lại theme của Bootstrap","description":"bootstrap, customize, theme","date":null,"path":"bootstrap - customize theme"},
{"category":"bootstrap","title":"Bootstrap dropdown","description":"notification, menu đa cấp (multilevel)","date":null,"path":"bootstrap - dropdown"},
{"category":"bootstrap","title":"Bootstrap 4 Flex","description":"Bootstrap 4 Flex","date":null,"path":"bootstrap - flex"},
{"category":"bootstrap","title":"Hướng dẫn thiết kế form với Bootstrap","description":"input, textarea, select, checkbox, radio, toggle switch, file input, range, button","date":null,"path":"bootstrap - form"},
{"category":"bootstrap","title":"Bootstrap","description":"Bootstrap","date":null,"path":"bootstrap - get started"},
{"category":"bootstrap","title":"Bootstrap Media","description":"Bootstrap Media tutorial","date":null,"path":"bootstrap - media"},
{"category":"bootstrap","title":"Bootstrap modal","description":"popup","date":null,"path":"bootstrap - modal"},
{"category":"bootstrap","title":"Bootstrap Navbar","description":"Bootstrap Navbar","date":null,"path":"bootstrap - navbar"},
{"category":"bootstrap","title":"Phân trang trong Bootstrap","description":"Phân trang trong Bootstrap","date":null,"path":"bootstrap - pagination"},
{"category":"bootstrap","title":"Popover","description":"Popover","date":null,"path":"bootstrap - popover"},
{"category":"bootstrap","title":"Bootstrap Example","description":"Bootstrap Example","date":null,"path":"bootstrap - progress bar"},
{"category":"bootstrap","title":"Các cột có cùng chiều cao","description":"flex, h-100","date":null,"path":"bootstrap - same height columns"},
{"category":"bootstrap","title":"Bootstrap spinner","description":"processing, loading","date":null,"path":"bootstrap - spinner"},
{"category":"bootstrap","title":"Bootstrap Tooltip","description":"Bootstrap Tooltip","date":null,"path":"bootstrap - tooltip"},
{"category":"bootstrap","title":"Bootstrap typography","description":"Bootstrap typography","date":null,"path":"bootstrap - typography"},
{"category":"bootstrap","title":"Các class tiện ích Bootstrap","description":"border, sizing, overflow, float, spacing","date":null,"path":"bootstrap - utilities"},
{"category":"bootstrap","title":"Bootstrap 5","description":"Version 5","date":null,"path":"bootstrap - version 5"},
{"category":"composer","title":"Sử dụng Composer","description":"Sử dụng Composer","date":null,"path":"composer - basic usage"},
{"category":"composer","title":"Cấu trúc thư mục của dự án dùng Composer","description":"psr-4, autoload","date":null,"path":"composer - folder structure"},
{"category":"composer","title":"Cài đặt Composer","description":"linux, composer, windows","date":null,"path":"composer - installation"},
{"category":"composer","title":"Locking trong Composer","description":"lock","date":null,"path":"composer - locking"},
{"category":"composer","title":"Ghi đè file thư viện PHP với Composer","description":"php","date":null,"path":"composer - override vendor classes"},
{"category":"composer","title":"Chỉ định version cho các package trong Composer","description":"composer version","date":null,"path":"composer - package version"},
{"category":"composer","title":"Cấu hình proxy cho Composer","description":"Composer proxy","date":null,"path":"composer - proxy"},
{"category":"composer","title":"Đưa thư viện lưu trên Packagist","description":"packagist","date":null,"path":"composer - publish packagist"},
{"category":"composer","title":"Composer require-dev","description":"Các package chỉ phục vụ lúc phát triển","date":null,"path":"composer - require-dev"},
{"category":"css","title":"CSS animation","description":"animate.css, slide in, anagram, reveal animations when scrolling, wow.js, pulse, box-shadow, zoom, grow, hover effect","date":null,"path":"css - animation"},
{"category":"css","title":"CSS Arrows","description":"CSS Arrows","date":null,"path":"css - arrows"},
{"category":"css","title":"Maintain Aspect Ratio","description":"Maintain Aspect Ratio","date":null,"path":"css - aspect ratio"},
{"category":"css","title":"Backdrop-filter","description":"Backdrop-filter","date":null,"path":"css - backdrop-filter"},
{"category":"css","title":"","description":"","date":null,"path":"css - background"},
{"category":"css","title":"","description":"","date":null,"path":"css - blend-mode"},
{"category":"css","title":"CSS box-shadow","description":"CSS box-shadow","date":null,"path":"css - box-shadow"},
{"category":"css","title":"Đổi style cho trường mà trình duyệt tự điền dữ liệu","description":"-webkit-autofill","date":null,"path":"css - change autofill style"},
{"category":"css","title":"","description":"","date":null,"path":"css - circular progress bar"},
{"category":"css","title":"Thuộc tính clip-path","description":"Tạo các shape đơn giản, shape-outside","date":null,"path":"css - clip-path"},
{"category":"css","title":"CSS column","description":"CSS column","date":null,"path":"css - column"},
{"category":"css","title":"Critical CSS","description":"Tách inline các CSS sử dụng","date":null,"path":"css - critical css"},
{"category":"css","title":"","description":"","date":null,"path":"css - css for print"},
{"category":"css","title":"CSS Selector","description":"Sử dụng ở cả CSS và JS để chọn phần tử","date":null,"path":"css - css selector"},
{"category":"css","title":"CSS Filters","description":"CSS Filters","date":null,"path":"css - filters"},
{"category":"css","title":"First-letter Selector","description":"Làm nổi bật chữ đầu tiên của đoạn văn","date":null,"path":"css - first letter selector"},
{"category":"css","title":"Giới thiệu Flexbox","description":"Giới thiệu Flexbox để xây dựng bố cục trang","date":null,"path":"css - flexbox introduction"},
{"category":"css","title":"CSS Layout - float and clear","description":"CSS Layout - float and clear","date":null,"path":"css - float"},
{"category":"css","title":"CSS font-weight","description":"CSS font-weight","date":null,"path":"css - font-weight"},
{"category":"css","title":"CSS Grid","description":"CSS Grid","date":null,"path":"css - grid"},
{"category":"css","title":"Ẩn mũi tên ở thẻ input number","description":"Ẩn mũi tên ở thẻ input number","date":null,"path":"css - hide arrows on number input"},
{"category":"css","title":"","description":"","date":null,"path":"css - image sprites"},
{"category":"css","title":"LESS - A CSS Pre-processor","description":"A CSS pre-processor","date":null,"path":"css - less"},
{"category":"css","title":"mix-blend-mode","description":"blend, css, video, background","date":null,"path":"css - mix-blend-mode"},
{"category":"css","title":"","description":"","date":null,"path":"css - multi-level menu"},
{"category":"css","title":"CSS The object-fit Property","description":"CSS The object-fit Property","date":null,"path":"css - object-fit"},
{"category":"css","title":"CSS Perspective","description":"CSS Perspective","date":null,"path":"css - perspective"},
{"category":"css","title":"CSS selector :placeholder-shown","description":"CSS selector :placeholder-shown","date":null,"path":"css - placeholder-shown"},
{"category":"css","title":"","description":"","date":null,"path":"css - position"},
{"category":"css","title":"Position sticky","description":"Position sticky","date":null,"path":"css - position sticky"},
{"category":"css","title":"","description":"","date":null,"path":"css - precedence"},
{"category":"css","title":"Sass","description":"Sửa dụng Sass để tổ chức CSS","date":null,"path":"css - sass"},
{"category":"css","title":"CSS Shapes","description":"CSS Shapes","date":null,"path":"css - shapes"},
{"category":"css","title":"Text stroke","description":"Viền của chữ","date":null,"path":"css - text stroke"},
{"category":"css","title":"Hiển thị dấu ba chấm khi text quá dài","description":"text-overflow, line-clamp","date":null,"path":"css - text-overflow"},
{"category":"css","title":"Cool Text Effects Using CSS Text-Shadow","description":"Cool Text Effects Using CSS Text-Shadow","date":null,"path":"css - text-shadow"},
{"category":"css","title":"Vertical Align Examples","description":"Vertical Align Examples","date":null,"path":"css - vertical align"},
{"category":"css","title":"Demo Roboto","description":"","date":null,"path":"css - web font"},
{"category":"css","title":"","description":"","date":null,"path":"css - word wrap"},
{"category":"deno","title":"Lập trình với Deno","description":"Sách","date":null,"path":"deno - deno book"},
{"category":"docker","title":"Docker Get Started","description":"Docker Get Started","date":null,"path":"docker - get started"},
{"category":"docker","title":"Tạo Docker container cho ứng dụng Laravel","description":"Tạo Docker container cho ứng dụng Laravel","date":null,"path":"docker - laravel container"},
{"category":"elasticsearch","title":"Elasticsearch Get started","description":"Elasticsearch Get started","date":null,"path":"elasticsearch - get started"},
{"category":"git","title":"Git Beginner's Guide for dummies","description":"Git Beginner's Guide for dummies","date":null,"path":"git - beginner's guide for dummies"},
{"category":"git","title":"Book cover","description":"Book cover","date":null,"path":"git - book cover"},
{"category":"git","title":"Kỹ thuật phân nhánh trong Git","description":"git branch","date":null,"path":"git - branch"},
{"category":"git","title":"Git cheatsheet","description":"Git","date":null,"path":"git - cheatsheet"},
{"category":"git","title":"Tìm hiểu về Commit và Staging Area trong Git","description":"Git","date":null,"path":"git - commit and staging area"},
{"category":"git","title":"Compare Revisions","description":"Compare Revisions","date":null,"path":"git - compare revisions"},
{"category":"git","title":"Tắt cảnh báo CRLF","description":"Disable CRLF warning","date":null,"path":"git - disable crlf warning"},
{"category":"git","title":"External Merge and Diff Tools","description":"External Merge and Diff Tools","date":null,"path":"git - external merge and diff tools"},
{"category":"git","title":"git và Github là gì? Tại sao nên dùng?","description":"git","date":null,"path":"git - git and github"},
{"category":"git","title":"Quy trình phân nhánh branch chuẩn","description":"git flow","date":null,"path":"git - git flow"},
{"category":"git","title":"git-chain","description":"git-chain","date":null,"path":"git - git-chain"},
{"category":"git","title":"GitHub Repo Size","description":"GitHub Repo Size","date":null,"path":"git - github repo size"},
{"category":"git","title":".gitignore","description":".gitignore","date":null,"path":"git - gitignore"},
{"category":"git","title":"Xem lịch sử thay đổi của một file","description":"gitk","date":null,"path":"git - history of a file"},
{"category":"git","title":"Cách tạo repository trong Git và Github","description":"Git","date":null,"path":"git - init repository"},
{"category":"git","title":"Cài đặt git và thiết lập ban đầu","description":"git","date":null,"path":"git - install and config"},
{"category":"git","title":"Giới thiệu serie git cơ bản","description":"git","date":null,"path":"git - introduction"},
{"category":"git","title":"Git","description":"Git","date":null,"path":"git - learning"},
{"category":"git","title":"Git log","description":"Git log","date":null,"path":"git - log and undo"},
{"category":"git","title":"Sử dụng proxy trong git","description":"git proxy","date":null,"path":"git - proxy"},
{"category":"git","title":"Git - Sơ lược Remote Repository và Git","description":"Git","date":null,"path":"git - remote repository and origin"},
{"category":"git","title":"Xoá file khỏi Git","description":"Remove files","date":null,"path":"git - remove files"},
{"category":"git","title":"Cách tự tạo Repository cho Git trên Server riêng","description":"Git","date":null,"path":"git - repository server"},
{"category":"git","title":"Loại bỏ các file đã thay đổi","description":"Git","date":null,"path":"git - revert modified files"},
{"category":"git","title":"Lưu mật khẩu git","description":"Save git password so you don't have to keep typing it when you pull/push something","date":null,"path":"git - save git password"},
{"category":"git","title":"Đánh tag với git","description":"Hướng dẫn tag (đánh dấu)","date":null,"path":"git - tag"},
{"category":"git","title":"Use SSH key with git","description":"Use SSH key with git","date":null,"path":"git - use ssh key"},
{"category":"highcharts","title":"Các ví dụ Highcharts","description":"demo","date":null,"path":"highcharts - examples"},
{"category":"highcharts","title":"Tìm hiểu Highcharts","description":"Tìm hiểu Highcharts","date":null,"path":"highcharts - learning"},
{"category":"highcharts","title":"Highcharts network graph","description":"Mind map","date":null,"path":"highcharts - network graph"},
{"category":"highmaps","title":"Bản đồ thế giới","description":"Map bubble, REST Countries API, Hiển thị thông tin các nước trên thế giới","date":null,"path":"highmaps - map bubble"},
{"category":"highmaps","title":"Bản đồ Việt Nam","description":"Bản đồ Việt Nam","date":null,"path":"highmaps - vietnamese"},
{"category":"it","title":"Buy a new PC","description":"Guideline to buy a new PC","date":null,"path":"it - buy pc"},
{"category":"it","title":"Check Application Alive","description":"Check Application Alive","date":null,"path":"it - check application alive"},
{"category":"it","title":"Kiểm tra định dạng file","description":"extension, mime","date":null,"path":"it - check file type"},
{"category":"it","title":"Cấu hình HTTPS cho ứng dụng web","description":"Cấu hình HTTPS cho ứng dụng web","date":null,"path":"it - config web https"},
{"category":"it","title":"Convert HTML to EPUB","description":"Convert HTML to EPUB","date":null,"path":"it - convert html to epub"},
{"category":"it","title":"Convert ảnh SVG thành PNG (resize luôn)","description":"icon, svgexport","date":null,"path":"it - convert svg to png"},
{"category":"it","title":"Cryptography","description":"Cryptography","date":null,"path":"it - cryptography"},
{"category":"it","title":"Câu lệnh curl","description":"Câu lệnh curl","date":null,"path":"it - curl"},
{"category":"it","title":"Kiểu dữ liệu datetime trong lập trình","description":"datetime","date":null,"path":"it - datetime"},
{"category":"it","title":"Cấu trúc file epub","description":"Cấu trúc file epub","date":null,"path":"it - epub format"},
{"category":"it","title":"Facebook","description":"","date":null,"path":"it - facebook api"},
{"category":"it","title":"Tạo Facebook app","description":"Tạo Facebook app","date":null,"path":"it - facebook app"},
{"category":"it","title":"","description":"","date":null,"path":"it - ffmpeg"},
{"category":"it","title":"File filter","description":"upcode, deploy","date":null,"path":"it - filefilter"},
{"category":"it","title":"Full-stack web developer","description":"Các công nghệ mà tôi sử dụng","date":"2020-02-18 22:47:00","path":"it - full-stack web developer"},
{"category":"it","title":"Cài đặt hệ điều hành và phần mềm","description":"Install OS and softwares","date":null,"path":"it - install os and softwares"},
{"category":"it","title":"Cài đặt proxy Squid trên Windows","description":"squid proxy, windows, open firewall port","date":null,"path":"it - install squid proxy on windows"},
{"category":"it","title":"Cài đặt WEMP stack","description":"windows, nginx, mariadb, php","date":null,"path":"it - install wemp stack"},
{"category":"it","title":"IT Companies","description":"IT Companies","date":null,"path":"it - it companies in vietnam"},
{"category":"it","title":"Lỗi ATTT link target=\"_blank\"","description":"security","date":null,"path":"it - link target blank"},
{"category":"it","title":"","description":"","date":null,"path":"it - link to iframe"},
{"category":"it","title":"Tính toán âm lịch","description":"vietnamese calendar","date":null,"path":"it - lunar calendar"},
{"category":"it","title":"Lấy thông tin file đa phương tiện với ffprobe","description":"Lấy thông tin file đa phương tiện với ffprobe","date":null,"path":"it - multimedia analyzer with ffprobe"},
{"category":"it","title":"Mutable và immutable","description":"Mutable và immutable","date":null,"path":"it - mutable and immutable"},
{"category":"it","title":"Tool ngrok","description":"Mang demo dự án web lên internet không cần deploy","date":null,"path":"it - ngrok"},
{"category":"it","title":"","description":"","date":null,"path":"it - oracle ddl query"},
{"category":"it","title":"Pass-by-reference và pass-by-value","description":"pass-by-reference, pass-by-value","date":null,"path":"it - pass-by-reference and pass-by-value"},
{"category":"it","title":"Trang web cá nhân","description":"GitHub Page","date":null,"path":"it - personal website"},
{"category":"it","title":"Thẻ picture","description":"Responsive src của ảnh","date":null,"path":"it - picture tag"},
{"category":"it","title":"Biểu thức chính quy","description":"regex nói chung, không phân biệt ngôn ngữ lập trình","date":null,"path":"it - regular expression"},
{"category":"it","title":"Mở web ở chế độ app","description":"shortcut","date":null,"path":"it - run chrome in application mode"},
{"category":"it","title":"Web server đơn giản","description":"Simple web server","date":null,"path":"it - simple web server"},
{"category":"it","title":"Single Sign-on","description":"sso, cookie, session, login","date":null,"path":"it - single sign-on"},
{"category":"it","title":"","description":"","date":null,"path":"it - social login"},
{"category":"it","title":"Social Share","description":"Thêm link chia sẻ qua Facebook, Google+, Twitter, LinkedIn, Pinterest, Email","date":null,"path":"it - social share"},
{"category":"it","title":"Thiết kế CSDL","description":"Database conventions","date":null,"path":"it - sql database conventions"},
{"category":"it","title":"","description":"","date":null,"path":"it - sql tuning"},
{"category":"it","title":"Unit test","description":"Unit test","date":null,"path":"it - unit test"},
{"category":"it","title":"Sử dụng SVG","description":"icon, map","date":null,"path":"it - using svg"},
{"category":"it","title":"Video streaming","description":"m3u8, ts, ffmpeg, nginx, rtmp, rtsp, camera","date":null,"path":"it - video streaming"},
{"category":"it","title":"Phần mềm VirtualBox","description":"Tạo máy ảo","date":"2020-02-19 22:40:00","path":"it - virtualbox"},
{"category":"it","title":"Công cụ soạn thảo Visual Studio Code","description":"VSCode","date":null,"path":"it - visual studio code"},
{"category":"it","title":"Chỉnh sửa trực tiếp với contenteditable","description":"Inline editing with contenteditable","date":null,"path":"it - web contenteditable"},
{"category":"it","title":"Web development roadmap","description":"From zero to deployment","date":"2020-02-18 22:48:00","path":"it - web development roadmap"},
{"category":"it","title":"Load balancer","description":"Cân bằng tải","date":null,"path":"it - web load balancer"},
{"category":"it","title":"Checklist ATTT cho ứng dụng web","description":"web security","date":null,"path":"it - web security checklist"},
{"category":"it","title":"Text track","description":"subtitle","date":null,"path":"it - webvtt"},
{"category":"java","title":"","description":"","date":null,"path":"java - apache common demo"},
{"category":"java","title":"apk to jar","description":"apk to jar","date":null,"path":"java - apk to jar"},
{"category":"java","title":"Compress","description":"Compress","date":null,"path":"java - compress"},
{"category":"java","title":"HTTP Server bằng Java thuần","description":"socket","date":null,"path":"java - core java http server"},
{"category":"java","title":"Crawler với Java","description":"Crawl các domain bằng Google theo từ khóa","date":null,"path":"java - crawler"},
{"category":"java","title":"","description":"","date":null,"path":"java - datetime"},
{"category":"java","title":"","description":"","date":null,"path":"java - db structure"},
{"category":"java","title":"","description":"","date":null,"path":"java - drm"},
{"category":"java","title":"Flying Saucer","description":"Flying Saucer","date":null,"path":"java - flying-saucer demo"},
{"category":"java","title":"Cài đặt IDE Eclipse","description":"Cài đặt IDE Eclipse","date":null,"path":"java - install eclipse"},
{"category":"java","title":"","description":"","date":null,"path":"java - java-demo"},
{"category":"java","title":"JODConverter","description":"JODConverter","date":null,"path":"java - jodconverter demo"},
{"category":"java","title":"Jsoup","description":"Jsoup","date":null,"path":"java - jsoup"},
{"category":"java","title":"Log Alert","description":"Cảnh báo khi có log lỗi","date":null,"path":"java - log alert"},
{"category":"java","title":"Bắt đầu với Maven","description":"eclipse","date":null,"path":"java - maven"},
{"category":"java","title":"PDF & DOC","description":"PDF & DOC","date":null,"path":"java - pdf doc"},
{"category":"js","title":"AJAX","description":"XMLHttpRequest vs Fetch API vs jQuery AJAX vs axios","date":null,"path":"js - ajax"},
{"category":"js","title":"Mảng trong JS","description":"Mảng trong JS","date":null,"path":"js - array"},
{"category":"js","title":"Arrow function","description":"Arrow function","date":null,"path":"js - arrow function"},
{"category":"js","title":"Thực hiện hàm không đồng bộ","description":"callback, promise, async, await","date":null,"path":"js - asynchronous"},
{"category":"js","title":"Audio and Microphone Visualizer","description":"Audio and Microphone Visualizer","date":null,"path":"js - audio and microphone visualizer"},
{"category":"js","title":"axios with cancellation","description":"axios with cancellation","date":null,"path":"js - axios with cancellation"},
{"category":"js","title":"Binary Data","description":"Binary Data","date":null,"path":"js - binary data"},
{"category":"js","title":"Using Blob","description":"Using Blob","date":null,"path":"js - blob"},
{"category":"js","title":"Bookmarklet","description":"Bookmarklet","date":null,"path":"js - bookmarklet"},
{"category":"js","title":"","description":"","date":null,"path":"js - breadth first search algorithm"},
{"category":"js","title":"Breaking a return statement","description":"Breaking a return statement","date":null,"path":"js - breaking a return statement"},
{"category":"js","title":"Browser console","description":"Browser console","date":null,"path":"js - browser console"},
{"category":"js","title":"Calculating week numbers in JS","description":"Calculating week numbers in JS","date":null,"path":"js - calculating week number"},
{"category":"js","title":"JS Canvas","description":"JS Canvas","date":null,"path":"js - canvas"},
{"category":"js","title":"CKEditor","description":"CKEditor","date":null,"path":"js - ckeditor"},
{"category":"js","title":"Clipboard","description":"Xử lý khi paste","date":null,"path":"js - clipboard"},
{"category":"js","title":"JS Closure","description":"closure, let, variable scope","date":null,"path":"js - closure"},
{"category":"js","title":"CommonUtils","description":"Các hàm dùng chung hay dùng","date":"2020-04-16 22:36:00","path":"js - common"},
{"category":"js","title":"Nối nhiều file audio vào làm một","description":"Nối nhiều file audio vào làm một","date":null,"path":"js - concatenating audio files with web audio api"},
{"category":"js","title":"Khai báo với const và let","description":"Khai báo với const và let","date":null,"path":"js - const and let"},
{"category":"js","title":"Contact Picker API","description":"Chọn từ danh bạ","date":"2020-02-11 21:30:00","path":"js - contact picker api"},
{"category":"js","title":"Cookie","description":"Cookie","date":null,"path":"js - cookie"},
{"category":"js","title":"Copy text","description":"Copy text","date":null,"path":"js - copy text"},
{"category":"js","title":"Custom Event","description":"Custom Event","date":null,"path":"js - custom event"},
{"category":"js","title":"Default parameter","description":"Default parameter","date":null,"path":"js - default parameter"},
{"category":"js","title":"Design patterns","description":"Design patterns","date":null,"path":"js - design patterns"},
{"category":"js","title":"Destructuring Assignment","description":"Destructuring Assignment","date":null,"path":"js - destructuring assignment"},
{"category":"js","title":"","description":"","date":null,"path":"js - dijkstra algorithm"},
{"category":"js","title":"DOM to Canvas animation","description":"HTML to Canvas animation","date":null,"path":"js - dom to canvas animation"},
{"category":"js","title":"Kéo thả trên web","description":"drag and drop, jquery ui sortable","date":null,"path":"js - drag and drop"},
{"category":"js","title":"Nhúng video vào trang web","description":"YouTube, Facebook","date":null,"path":"js - embed youtube video"},
{"category":"js","title":"EPUB reader","description":"epub reader","date":null,"path":"js - epub reader (bibi)"},
{"category":"js","title":"EPUB reader","description":"epub reader","date":null,"path":"js - epub reader (futurepress epub)"},
{"category":"js","title":"JS - ES6","description":"Các tính năng mới và hay trong JS","date":null,"path":"js - es6"},
{"category":"js","title":"Sử dụng ESLint","description":"lint, vscode","date":null,"path":"js - eslint"},
{"category":"js","title":"Event Delegation","description":"matches, closet","date":null,"path":"js - event delegation"},
{"category":"js","title":"JS event","description":"JS event","date":null,"path":"js - events"},
{"category":"js","title":"Export và import file Excel với JS","description":"exceljs","date":null,"path":"js - excel"},
{"category":"js","title":"","description":"","date":null,"path":"js - exception"},
{"category":"js","title":"document.execCommand","description":"WYSIWYG editor","date":null,"path":"js - execcommand"},
{"category":"js","title":"Xuất file docx với JS","description":"word document","date":null,"path":"js - export docx"},
{"category":"js","title":"Thêm Facebook comment vào trang","description":"Thêm Facebook comment vào trang","date":null,"path":"js - facebook comment"},
{"category":"js","title":"Display Webcam Stream","description":"Display Webcam Stream","date":null,"path":"js - fake webcam"},
{"category":"js","title":"","description":"","date":null,"path":"js - file api"},
{"category":"js","title":"Save and load text file by JS","description":"save, download, load","date":"2020-02-24 22:05:00","path":"js - file saver"},
{"category":"js","title":"JS full text search","description":"lunr, fuse","date":null,"path":"js - full text search"},
{"category":"js","title":"","description":"","date":null,"path":"js - fullpage.js"},
{"category":"js","title":"fullPage.js with animate.css","description":"fullPage.js with animate.css","date":null,"path":"js - fullpage.js with animate.css"},
{"category":"js","title":"Wow.js Animate.css text animation","description":"Wow.js Animate.css text animation","date":null,"path":"js - fullpage.js with wow.js"},
{"category":"js","title":"Full-screen API","description":"Chế độ toàn màn hình","date":null,"path":"js - fullscreen"},
{"category":"js","title":"JS function","description":"JS function","date":null,"path":"js - function"},
{"category":"js","title":"JS functional programming","description":"JS functional programming","date":null,"path":"js - functional programming"},
{"category":"js","title":"JS generator","description":"JS generator","date":null,"path":"js - generator"},
{"category":"js","title":"Geolocation","description":"Geolocation","date":null,"path":"js - geolocation"},
{"category":"js","title":"Get Computed CSS","description":"Get computed CSS","date":null,"path":"js - get computed css"},
{"category":"js","title":"Lấy giá trị tham số từ URL bằng JS","description":"Lấy giá trị tham số từ URL bằng JS","date":null,"path":"js - get parameter"},
{"category":"js","title":"Getter, setter trong JS","description":"getter, setter, getset","date":null,"path":"js - getset"},
{"category":"js","title":"Gio.js","description":"3D globe, map","date":null,"path":"js - giojs"},
{"category":"js","title":"Google Drive API","description":"upload file, create folder","date":null,"path":"js - google drive api"},
{"category":"js","title":"","description":"","date":null,"path":"js - google map"},
{"category":"js","title":"Google Sheet API","description":"Google Sheet API","date":null,"path":"js - google sheet api"},
{"category":"js","title":"Sử dụng Google Translate API","description":"Dịch tiếng Anh sang tiếng Việt","date":null,"path":"js - google translate api"},
{"category":"js","title":"Bắt đầu với Gulp","description":"Bắt đầu với Gulp","date":null,"path":"js - gulp"},
{"category":"js","title":"Highlight source code syntax","description":"highlight.js","date":null,"path":"js - highlightjs"},
{"category":"js","title":"History API","description":"history","date":null,"path":"js - history api"},
{"category":"js","title":"HTML sanitizer","description":"HTML sanitizer","date":null,"path":"js - html sanitizer"},
{"category":"js","title":"Image Loader","description":"css, js, image loader","date":null,"path":"js - image loader"},
{"category":"js","title":"Marvinj","description":"Xử lý ảnh","date":null,"path":"js - image processing (marvinj)"},
{"category":"js","title":"Infinite scroll","description":"Load tiếp bản ghi khi kéo xuống cuối trang","date":null,"path":"js - infinite scroll"},
{"category":"js","title":"insertAdjacentHTML","description":"insertAdjacentHTML","date":null,"path":"js - insertadjacenthtml"},
{"category":"js","title":"Unit test với Jest","description":"Unit test với Jest","date":"2020-02-27 10:22:00","path":"js - jest (unit test)"},
{"category":"js","title":"jQuery comment","description":"Một thư viện về comment rất hay","date":null,"path":"js - jquery-comments"},
{"category":"js","title":"JS năm 2016","description":"Bức tranh toàn cảnh JS năm 2016","date":null,"path":"js - js in 2016"},
{"category":"js","title":"","description":"","date":null,"path":"js - json form binding"},
{"category":"js","title":"Bắt sự kiện nhập từ bàn phím","description":"Key event","date":null,"path":"js - key event"},
{"category":"js","title":"Key Sequence Detection","description":"keyboard","date":null,"path":"js - key sequence detection"},
{"category":"js","title":"Keyboard input handler","description":"Keyboard input handler","date":null,"path":"js - keyboard input"},
{"category":"js","title":"Live Reload","description":"Live Reload","date":null,"path":"js - live reload"},
{"category":"js","title":"Load file JS async và defer","description":"Load file JS async và defer","date":null,"path":"js - load file async and defer"},
{"category":"js","title":"Toán tử logic và biểu thức gán","description":"Toán tử logic và biểu thức gán","date":null,"path":"js - logical assignment"},
{"category":"js","title":"Masked Input","description":"Masked Input","date":null,"path":"js - masked input"},
{"category":"js","title":"Mergely diff demo","description":"Mergely diff demo","date":null,"path":"js - mergely diff demo"},
{"category":"js","title":"MIDIjs","description":"MIDIjs","date":null,"path":"js - midi player"},
{"category":"js","title":"","description":"","date":null,"path":"js - mobile number"},
{"category":"js","title":"Module","description":"module.exports, exports - require (Node), export - import (ES6)","date":null,"path":"js - module"},
{"category":"js","title":"Monitoring DOM changes","description":"Monitoring DOM changes","date":null,"path":"js - monitering dom changes"},
{"category":"js","title":"","description":"","date":null,"path":"js - multi-language"},
{"category":"js","title":"","description":"","date":null,"path":"js - my own repeat template"},
{"category":"js","title":"Notification API","description":"Thông báo hệ thống","date":null,"path":"js - notification api"},
{"category":"js","title":"Nullish coalescing","description":"Hợp nhất null, falsy, truthy","date":null,"path":"js - nullish coalescing"},
{"category":"js","title":"Dấu phân cách số","description":"Dấu phân cách số","date":null,"path":"js - numeric separator"},
{"category":"js","title":"Làm rối code JS","description":"Làm rối code JS","date":null,"path":"js - obfuscate code"},
{"category":"js","title":"Object literal","description":"Khai báo đối tượng","date":null,"path":"js - object literal"},
{"category":"js","title":"","description":"","date":null,"path":"js - onbeforeunload"},
{"category":"js","title":"","description":"","date":null,"path":"js - onmousedown"},
{"category":"js","title":"Lập trình hướng đối tượng trong JS","description":"class, object oriented programming","date":null,"path":"js - oop"},
{"category":"js","title":"Optional chaining","description":"Optional chaining","date":null,"path":"js - optional chaining"},
{"category":"js","title":"Output pretty JSON","description":"Output pretty JSON","date":null,"path":"js - output pretty json"},
{"category":"js","title":"Page scroll","description":"Page scroll","date":null,"path":"js - page scroll"},
{"category":"js","title":"","description":"","date":null,"path":"js - page visibility api"},
{"category":"js","title":"Paginate Text","description":"Paginate Text","date":null,"path":"js - paginate text"},
{"category":"js","title":"","description":"","date":null,"path":"js - parseint"},
{"category":"js","title":"Perfect Scrollbar","description":"perfect-scrollbar","date":null,"path":"js - perfect scrollbar"},
{"category":"js","title":"Picture-in-Picture","description":"Picture-in-Picture Web API","date":null,"path":"js - picture in picture"},
{"category":"js","title":"Playing an MP3 file with the Web Audio API","description":"Playing an MP3 file with the Web Audio API","date":null,"path":"js - playing an mp3 file with web audio api"},
{"category":"js","title":"Không cho phép copy content từ web","description":"Không cho phép copy content từ web","date":null,"path":"js - prevent copy content"},
{"category":"js","title":"Private field","description":"Private field trong class","date":null,"path":"js - private field"},
{"category":"js","title":"Private method","description":"Private method","date":null,"path":"js - private method"},
{"category":"js","title":"Proxy trong JS","description":"proxy","date":null,"path":"js - proxy"},
{"category":"js","title":"Pure JS PubSub System","description":"Pure JS PubSub System","date":null,"path":"js - pure pubsub"},
{"category":"js","title":"Push API","description":"Push API","date":null,"path":"js - push api"},
{"category":"js","title":"Bắt đầu với PWA","description":"pwa, Progressive Web App","date":null,"path":"js - pwa"},
{"category":"js","title":"QR code","description":"Generator, scanner, quick","date":"2020-02-12 22:00:00","path":"js - qr code"},
{"category":"js","title":"","description":"","date":null,"path":"js - refer to parent from iframe"},
{"category":"js","title":"Biểu thức chính quy trong JS","description":"regex","date":null,"path":"js - regular expression"},
{"category":"js","title":"Get relative mouse coordinate","description":"Get relative mouse coordinate","date":null,"path":"js - relative mouse coordinate"},
{"category":"js","title":"Phương thức String replace trong JS","description":"str.replace()","date":null,"path":"js - replace function"},
{"category":"js","title":"requestAnimationFrame","description":"requestAnimationFrame","date":null,"path":"js - requestanimationframe"},
{"category":"js","title":"Rest Parameter","description":"Rest Parameter","date":null,"path":"js - rest parameters"},
{"category":"js","title":"Right click context menu","description":"Right click context menu","date":null,"path":"js - right click context menu"},
{"category":"js","title":"Riot","description":"Riot","date":null,"path":"js - riot"},
{"category":"js","title":"","description":"","date":null,"path":"js - say numbers"},
{"category":"js","title":"Lấy kích thước màn hình","description":"dimension","date":null,"path":"js - screen size"},
{"category":"js","title":"Chụp ảnh màn hình","description":"chụp ảnh màn hình để thông báo lỗi, export image report, dom-to-image, html2canvas, rasterizehtml, webext, invalid xml characters","date":null,"path":"js - screenshot"},
{"category":"js","title":"Simple Multi-language translation","description":"Simple Multi-language translation","date":null,"path":"js - simple multi-language translation"},
{"category":"js","title":"Slide up and down","description":"Slide up and down","date":null,"path":"js - slide up down"},
{"category":"js","title":"Sắp xếp tiếng Việt","description":"Sắp xếp tiếng Việt","date":null,"path":"js - sort vietnamese"},
{"category":"js","title":"","description":"","date":null,"path":"js - spatial navigation"},
{"category":"js","title":"Nhận dạng tiếng nói","description":"speech recognition, voice input, asr","date":null,"path":"js - speech recognition"},
{"category":"js","title":"Spread Operator","description":"Spread Operator","date":null,"path":"js - spread operator"},
{"category":"js","title":"JS Spread syntax","description":"JS Spread syntax","date":null,"path":"js - spread syntax"},
{"category":"js","title":"Storage API","description":"IndexedDB","date":null,"path":"js - storage quota"},
{"category":"js","title":"Các phương thức của String trong JS","description":"Các phương thức của String trong JS","date":null,"path":"js - string methods"},
{"category":"js","title":"Phương thức String.prototype.replaceAll","description":"Phương thức String.prototype.replaceAll","date":null,"path":"js - string replaceall"},
{"category":"js","title":"Convert String to ArrayBuffer","description":"Convert String to ArrayBuffer","date":null,"path":"js - string to arraybuffer"},
{"category":"js","title":"Summernote","description":"A simple editor","date":null,"path":"js - summernote"},
{"category":"js","title":"Symbol trong JS","description":"Symbol","date":null,"path":"js - symbol"},
{"category":"js","title":"Template string","description":"Template string","date":null,"path":"js - template string"},
{"category":"js","title":"Tổng hợp tiếng nói","description":"Text to speech, speech synthesis","date":null,"path":"js - text to speech"},
{"category":"js","title":"Tự sinh mục lục","description":"Table of content","date":null,"path":"js - toc"},
{"category":"js","title":"","description":"","date":null,"path":"js - typescript"},
{"category":"js","title":"Preview file ảnh","description":"Upload image preview","date":null,"path":"js - upload image preview"},
{"category":"js","title":"Upload nhiều file","description":"Cho phép chọn nhiều file, từng file một. Có thể bỏ bớt file. Submit sau đó cùng các thông tin khác.","date":null,"path":"js - upload multiple files"},
{"category":"js","title":"Vara.js","description":"Simulate signature animation","date":null,"path":"js - vara"},
{"category":"js","title":"","description":"","date":null,"path":"js - vietkey"},
{"category":"js","title":"Wavesurfer","description":"Wavesurfer","date":null,"path":"js - wavesurfer"},
{"category":"js","title":"Web Socket","description":"Web Socket client, chat","date":null,"path":"js - web socket"},
{"category":"js","title":"","description":"","date":null,"path":"js - window open function"},
{"category":"js","title":"Nén và giải nén ZIP file","description":"zip","date":null,"path":"js - zip"},
{"category":"laravel","title":"Laravel Artisan","description":"Thực hiện các lệnh PHP artisan","date":null,"path":"laravel - artisan"},
{"category":"laravel","title":"Xác thực với Laravel","description":"Đăng ký, đăng nhập, đăng xuất, quên mật khẩu","date":"2020-02-23 21:50:00","path":"laravel - authentication"},
{"category":"laravel","title":"Phân quyền trong Laravel","description":"Laravel authorization","date":null,"path":"laravel - authorization"},
{"category":"laravel","title":"Blade template","description":"Blade template","date":null,"path":"laravel - blade template"},
{"category":"laravel","title":"Laravel Pusher","description":"Laravel Pusher","date":null,"path":"laravel - broadcasting with pusher"},
{"category":"laravel","title":"Xử lý cache trong Laravel","description":"Xử lý cache trong Laravel","date":null,"path":"laravel - cache"},
{"category":"laravel","title":"Laravel Cheat Sheet","description":"Laravel Cheat Sheet","date":null,"path":"laravel - cheat sheet"},
{"category":"laravel","title":"Cấu hình Laravel","description":"env","date":null,"path":"laravel - configuration"},
{"category":"laravel","title":"Laravel Contract","description":"Laravel Contract","date":null,"path":"laravel - contract"},
{"category":"laravel","title":"Laravel Controller","description":"Laravel Controller","date":null,"path":"laravel - controller"},
{"category":"laravel","title":"Laravel Cookie","description":"Laravel Cookie","date":null,"path":"laravel - cookie"},
{"category":"laravel","title":"Tạo hàm dùng chung","description":"Tạo hàm dùng chung","date":null,"path":"laravel - create helper functions"},
{"category":"laravel","title":"Phòng chống lỗi ATTT CSRF","description":"Phòng chống lỗi ATTT CSRF","date":null,"path":"laravel - csrf"},
{"category":"laravel","title":"Laravel Custom Webpack Configuration","description":"Laravel Custom Webpack Configuration","date":null,"path":"laravel - custom webpack configuration"},
{"category":"laravel","title":"Laravel Database","description":"Laravel Database","date":null,"path":"laravel - database"},
{"category":"laravel","title":"Triển khai ứng dụng Laravel","description":"No application encryption key has been specified","date":null,"path":"laravel - deploy"},
{"category":"laravel","title":"Laravel Eloquent","description":"Laravel Eloquent","date":null,"path":"laravel - eloquent"},
{"category":"laravel","title":"Laravel Eloquent Collections","description":"Laravel Eloquent Collections","date":null,"path":"laravel - eloquent collections"},
{"category":"laravel","title":"Laravel Eloquent fill method","description":"Laravel Eloquent fill method","date":null,"path":"laravel - eloquent fill method"},
{"category":"laravel","title":"Laravel Eloquent Mutators","description":"Laravel Eloquent Mutators","date":null,"path":"laravel - eloquent mutators"},
{"category":"laravel","title":"Laravel Eloquent Relationships","description":"Laravel Eloquent Relationships","date":null,"path":"laravel - eloquent relationships"},
{"category":"laravel","title":"Laravel Eloquent Serialization","description":"Laravel Eloquent Serialization","date":null,"path":"laravel - eloquent serialization"},
{"category":"laravel","title":"Laravel Email Verification","description":"Laravel Email Verification","date":null,"path":"laravel - email verification"},
{"category":"laravel","title":"Laravel Encryption","description":"Mã hóa, cryptography","date":null,"path":"laravel - encryption"},
{"category":"laravel","title":"Laravel Error","description":"Laravel Error","date":null,"path":"laravel - error"},
{"category":"laravel","title":"Laravel Events","description":"Laravel Events","date":null,"path":"laravel - events"},
{"category":"laravel","title":"Laravel Excel","description":"Laravel Excel, import, export","date":null,"path":"laravel - excel"},
{"category":"laravel","title":"Laravel Facade","description":"Laravel Facade","date":null,"path":"laravel - facade"},
{"category":"laravel","title":"Laravel Filesystem","description":"Quản lý file (upload) với Laravel","date":null,"path":"laravel - filesystem"},
{"category":"laravel","title":"Laravel Folder Structure","description":"Laravel Folder Structure","date":null,"path":"laravel - folder structure"},
{"category":"laravel","title":"Laravel frontend","description":"Laravel frontend","date":null,"path":"laravel - frontend"},
{"category":"laravel","title":"Lấy câu SQL","description":"Lấy câu SQL","date":null,"path":"laravel - get sql string"},
{"category":"laravel","title":"Bắt đầu học Laravel","description":"Bắt đầu học Laravel","date":null,"path":"laravel - get started"},
{"category":"laravel","title":"Laravel Hashing","description":"Laravel Hashing","date":null,"path":"laravel - hashing"},
{"category":"laravel","title":"Các hàm helper","description":"Các hàm helper","date":null,"path":"laravel - helpers"},
{"category":"laravel","title":"Laravel i18n","description":"Laravel i18n","date":null,"path":"laravel - i18n"},
{"category":"laravel","title":"Cài đặt Laravel","description":"Khởi tạo dự án mới","date":"2020-02-23 21:31:00","path":"laravel - installation"},
{"category":"laravel","title":"JWT (JSON Web Token) trong Laravel","description":"jwt, laravel","date":null,"path":"laravel - jwt"},
{"category":"laravel","title":"Laravel Khoa Pham Videos","description":"Laravel Khoa Pham Videos","date":null,"path":"laravel - khoa pham course"},
{"category":"laravel","title":"Quản lý log trong Laravel","description":"logging","date":null,"path":"laravel - logging"},
{"category":"laravel","title":"Gửi mail với Laravel","description":"Laravel mail","date":null,"path":"laravel - mail"},
{"category":"laravel","title":"Chế độ bảo trì","description":"upgrade, update","date":null,"path":"laravel - maintainace mode"},
{"category":"laravel","title":"Laravel Middleware","description":"Laravel Middleware","date":null,"path":"laravel - middleware"},
{"category":"laravel","title":"Laravel Migrations","description":"Laravel Migrations","date":null,"path":"laravel - migrations"},
{"category":"laravel","title":"Laravel Mix","description":"Compile, minimize file CSS, JS","date":null,"path":"laravel - mix"},
{"category":"laravel","title":"Thêm thư mục Models trong Laravel","description":"Thêm thư mục Models trong Laravel","date":null,"path":"laravel - models folder"},
{"category":"laravel","title":"Laravel Database Notification","description":"Laravel Database Notification","date":null,"path":"laravel - notification"},
{"category":"laravel","title":"Xác thực OAuth 2 với Laravel","description":"Xác thực OAuth 2 với Laravel","date":null,"path":"laravel - oauth 2 with passport"},
{"category":"laravel","title":"Phân trang trong Laravel","description":"Laravel Pagination","date":null,"path":"laravel - pagination"},
{"category":"laravel","title":"Laravel Query Builder","description":"Laravel Query Builder","date":null,"path":"laravel - query builder"},
{"category":"laravel","title":"Hàng đợi trong Laravel","description":"Xử lý công việc kiểu background, hàng đợi với Laravel","date":null,"path":"laravel - queue"},
{"category":"laravel","title":"Giới hạn truy cập với Laravel","description":"Laravel Rate Limit","date":null,"path":"laravel - rate limit"},
{"category":"laravel","title":"Laravel Redis","description":"Laravel Redis","date":null,"path":"laravel - redis"},
{"category":"laravel","title":"Laravel Request","description":"Laravel Request","date":null,"path":"laravel - request"},
{"category":"laravel","title":"Laravel đã xử lý một request như thế nào?","description":"service provider","date":null,"path":"laravel - request life cycle"},
{"category":"laravel","title":"Reset mật khẩu với Laravel","description":"Thực hiện chức năng quên mật khẩu trong Laravel","date":null,"path":"laravel - reset password"},
{"category":"laravel","title":"Laravel Response","description":"Laravel Response","date":null,"path":"laravel - response"},
{"category":"laravel","title":"Laravel route, url, asset","description":"Laravel route, url, asset","date":null,"path":"laravel - route, url, asset"},
{"category":"laravel","title":"Laravel Routing","description":"Laravel Routing","date":null,"path":"laravel - routing"},
{"category":"laravel","title":"Laravel Scheduling","description":"Thực hiện các tiến trình đặt lịch với Laravel","date":null,"path":"laravel - scheduling"},
{"category":"laravel","title":"Laravel Scout","description":"Laravel Scout","date":null,"path":"laravel - scout"},
{"category":"laravel","title":"Laravel Seeding","description":"Thêm dữ liệu vào database","date":null,"path":"laravel - seeding"},
{"category":"laravel","title":"Laravel Service Container","description":"Laravel Service Container","date":null,"path":"laravel - service container"},
{"category":"laravel","title":"Laravel Service Provider","description":"Laravel Service Provider","date":null,"path":"laravel - service provider"},
{"category":"laravel","title":"Quản lý session trong Laravel","description":"Laravel session","date":null,"path":"laravel - session"},
{"category":"laravel","title":"Sharing data between views","description":"Sharing data between views","date":null,"path":"laravel - sharing data between views"},
{"category":"laravel","title":"Laravel Socialite","description":"Laravel Socialite","date":null,"path":"laravel - socialite"},
{"category":"laravel","title":"Kiểm thử với Laravel","description":"Kiểm thử với Laravel","date":null,"path":"laravel - testing"},
{"category":"laravel","title":"Xác thực 2 lớp với Laravel","description":"google authenticator, time-based one-time password, totp, 2fa, mac, hmac","date":null,"path":"laravel - two-factor authentication"},
{"category":"laravel","title":"Upgrading To 5.7 From 5.6","description":"Upgrading To 5.7 From 5.6","date":null,"path":"laravel - upgrading to version 5.7 from 5.6"},
{"category":"laravel","title":"Upload file với Laravel","description":"xử lý và validate upload file với laravel","date":null,"path":"laravel - upload file"},
{"category":"laravel","title":"Sử dụng collate của MySQL trong Laravel","description":"Sử dụng collate của MySQL trong Laravel","date":null,"path":"laravel - use mysql colllate"},
{"category":"laravel","title":"Validation trong Laravel","description":"strong password","date":null,"path":"laravel - validation"},
{"category":"laravel","title":"Laravel 7","description":"Laravel 7 có gì mới","date":null,"path":"laravel - version 7"},
{"category":"laravel","title":"Laravel View","description":"Laravel View","date":null,"path":"laravel - view"},
{"category":"laravel","title":"Laravel View Composer","description":"Laravel View Composer","date":null,"path":"laravel - view composer"},
{"category":"laravel","title":"Cấu hình Voyager","description":"Cấu hình Voyager","date":null,"path":"laravel - voyager configuration"},
{"category":"laravel","title":"Giới thiệu Voyager","description":"laravel, admin, voyager","date":null,"path":"laravel - voyager get started"},
{"category":"linux","title":"Hướng dẫn sử dụng lệnh apt","description":"Hướng dẫn sử dụng lệnh apt","date":null,"path":"linux - apt command"},
{"category":"linux","title":"Crontab","description":"Crontab","date":null,"path":"linux - crontab"},
{"category":"linux","title":"","description":"","date":null,"path":"linux - customize computer style"},
{"category":"linux","title":"Disable IPv6","description":"Disable IPv6","date":null,"path":"linux - disable ipv6"},
{"category":"linux","title":"Force cp to overwrite without confirmation","description":"Force cp to overwrite without confirmation","date":null,"path":"linux - force copy"},
{"category":"linux","title":"Cài đặt GlusterFS","description":"GlusterFS","date":"2020-02-23 01:01:01","path":"linux - install glusterfs"},
{"category":"linux","title":"Cài đặt LEMP stack trên CentOS","description":"centos, nginx, mariadb, php, redis","date":null,"path":"linux - install lemp stack on centos"},
{"category":"linux","title":"Cài đặt MySQL trên Ubuntu","description":"Cài đặt MySQL trên Ubuntu","date":"2020-02-21 22:56:00","path":"linux - install mysql"},
{"category":"linux","title":"Cài đặt nginx trên Ubuntu","description":"linux, nginx, ubuntu, selinux","date":"2020-02-20 21:53:00","path":"linux - install nginx"},
{"category":"linux","title":"Cài đặt Node","description":"nvm","date":"2020-02-21 19:02:00","path":"linux - install node"},
{"category":"linux","title":"Cài đặt OracleJDK trên Linux","description":"OpenJDK, OracleJDK, jdk","date":null,"path":"linux - install oracle jdk"},
{"category":"linux","title":"Cài đặt PHP trên Ubuntu","description":"php8","date":"2020-02-19 23:54:00","path":"linux - install php"},
{"category":"linux","title":"Cài đặt Ubuntu Server","description":"Ubuntu Server, VirtualBox","date":"2020-02-19 23:15:00","path":"linux - install ubuntu server"},
{"category":"linux","title":"Hướng dẫn cài bộ gõ tiếng Việt trên Ubuntu","description":"ibus-unikey","date":null,"path":"linux - install vietnamese input method on ubuntu"},
{"category":"linux","title":"Giữ tiến trình luôn chạy","description":"Giữ tiến trình luôn chạy trên Linux","date":null,"path":"linux - keep app alive"},
{"category":"linux","title":"Các phiên bản Linux Mint","description":"Phiên bản Ubuntu tương ứng","date":"2020-04-05 16:10:00","path":"linux - linux mint version history"},
{"category":"linux","title":"Mount ổ cứng","description":"Mount ổ cứng","date":null,"path":"linux - mount"},
{"category":"linux","title":"Phân quyền trong Linux","description":"selinux, umask, chmod, find","date":null,"path":"linux - permission"},
{"category":"linux","title":"Chỉnh sửa ảnh","description":"resize, convert, modify, image processing, imagemagick","date":null,"path":"linux - resize, convert and modify images"},
{"category":"linux","title":"Lệnh rsync","description":"Đồng bộ file giữa hai server, sync","date":null,"path":"linux - rsync command"},
{"category":"linux","title":"Chạy PHP với nginx","description":"php-fpm","date":"2020-02-20 22:24:00","path":"linux - run php with nginx"},
{"category":"linux","title":"Quản lý service","description":"Service management","date":null,"path":"linux - service management"},
{"category":"linux","title":"Cấu hình path trên Linux","description":"Setting path","date":null,"path":"linux - setting path"},
{"category":"linux","title":"Thiết lập môi trường lab","description":"Thiết lập môi trường lab","date":"2020-02-19 22:41:00","path":"linux - setup lab environment"},
{"category":"linux","title":"Sử dụng SSH","description":"passwordless","date":"2020-02-19 23:27:00","path":"linux - ssh"},
{"category":"linux","title":"SSH port forward","description":"ssh tunnel","date":null,"path":"linux - ssh port forwarding"},
{"category":"linux","title":"The Differences between su, sudo su, sudo -s and sudo -i","description":"The Differences between su, sudo su, sudo -s and sudo -i","date":null,"path":"linux - sudo"},
{"category":"linux","title":"User và group trong Linux","description":"permission","date":null,"path":"linux - user and group"},
{"category":"linux","title":"Hướng dẫn sử dụng vi","description":"Hướng dẫn sử dụng vi","date":null,"path":"linux - vi editor"},
{"category":"linux","title":"Nhập tiếng Việt trong vim","description":"Nhập tiếng Việt trong vim","date":null,"path":"linux - vietnamese input method"},
{"category":"linux","title":"Hiển thị cây thư mục","description":"ls, directory","date":null,"path":"linux - view folder tree"},
{"category":"mysql","title":"Character Set và Collation trong MySQL","description":"Tìm kiếm, so sánh, sắp xếp tiếng Việt, không phân biệt hoa thường","date":null,"path":"mysql - character set and collation"},
{"category":"mysql","title":"Common Table Expression (CTE)","description":"Common Table Expression (CTE)","date":null,"path":"mysql - common table exrepssion (cte)"},
{"category":"mysql","title":"Tạo mới người dùng và gán quyền trong","description":"How to create a new user and grant permissions in MySQL","date":null,"path":"mysql - create a new user and grant permissions"},
{"category":"mysql","title":"Các kiểu dữ liệu trong MySQL","description":"mysql","date":null,"path":"mysql - data types"},
{"category":"mysql","title":"Phân tích câu lệnh MySQL với explain","description":"Phân tích câu lệnh MySQL với explain","date":null,"path":"mysql - explain"},
{"category":"mysql","title":"Full text search trong MySQL","description":"MySQL Full text search","date":null,"path":"mysql - full text search"},
{"category":"mysql","title":"Học MySQL","description":"Học MySQL","date":null,"path":"mysql - get started"},
{"category":"mysql","title":"Import và export MySQL","description":"mysql, import, export","date":null,"path":"mysql - import and export"},
{"category":"mysql","title":"Sử dụng index trong MySQL","description":"Sử","date":null,"path":"mysql - index"},
{"category":"mysql","title":"Kiểu dữ liệu JSON","description":"json, mariadb","date":null,"path":"mysql - json data type"},
{"category":"mysql","title":"Lưu file (ảnh) dạng binary trong MySQL","description":"Lưu file (ảnh) dạng binary trong MySQL","date":null,"path":"mysql - store binary file"},
{"category":"mysql","title":"","description":"","date":null,"path":"mysql - type date"},
{"category":"mysql","title":"Window function","description":"Window function","date":null,"path":"mysql - window function"},
{"category":"nginx","title":"Liệt kê thư mục","description":"Liệt kê thư mục","date":null,"path":"nginx - autoindex"},
{"category":"nginx","title":"Block với nginx","description":"Block với nginx","date":null,"path":"nginx - block"},
{"category":"nginx","title":"Thay đổi user chạy Nginx Server và PHP-FPM","description":"Thay đổi user chạy Nginx Server và PHP-FPM","date":null,"path":"nginx - change run user"},
{"category":"nginx","title":"Cấu hình nginx","description":"Cấu hình nginx","date":null,"path":"nginx - configuration"},
{"category":"nginx","title":"Tìm hiểu nginx","description":"Tìm hiểu nginx","date":null,"path":"nginx - get started"},
{"category":"nginx","title":"Nginx Load Balancer","description":"Nginx Load Balancer","date":null,"path":"nginx - load balancer"},
{"category":"nginx","title":"Cấu hình location trong nginx","description":"Cấu hình location trong nginx","date":null,"path":"nginx - location configuration"},
{"category":"nginx","title":"Nginx Reverse Proxy","description":"Nginx Reverse Proxy","date":null,"path":"nginx - reverse proxy"},
{"category":"node","title":"Đóng gói dự án Node thành một file js","description":"ncc, pkg, nexe, jsbin","date":null,"path":"node - bundle single executable"},
{"category":"node","title":"Electron","description":"electron, node, npm proxy","date":null,"path":"node - electron"},
{"category":"node","title":"Cấu hình proxy cho npm","description":"Configure proxy to install Node package","date":null,"path":"node - npm proxy"},
{"category":"php","title":"Mảng trong PHP","description":"Mảng trong PHP","date":null,"path":"php - array"},
{"category":"php","title":"","description":"","date":null,"path":"php - async event driven (websocket) workerman"},
{"category":"php","title":"Autoload trong PHP","description":"Autoload trong PHP","date":null,"path":"php - autoload"},
{"category":"php","title":"Block request PHP trên Windows","description":"php-fpm, FastCGI, CGI, PHP_FCGI_CHILDREN","date":null,"path":"php - block request on windows"},
{"category":"php","title":"Các giá trị, hàm boolean trong PHP","description":"falsy, isset, empty, is_null, elvis operator, null-coalescing operator","date":null,"path":"php - boolean"},
{"category":"php","title":"Hàm callback trong PHP","description":"Hàm callback trong PHP","date":null,"path":"php - callback function"},
{"category":"php","title":"","description":"","date":null,"path":"php - character encoding"},
{"category":"php","title":"PHP Closure","description":"PHP Closure","date":null,"path":"php - closure"},
{"category":"php","title":"Hàm compact","description":"Hàm compact","date":null,"path":"php - compact function"},
{"category":"php","title":"Cấu hình upload size cho PHP","description":"upload, 413 Request Entity Too Large","date":null,"path":"php - config upload"},
{"category":"php","title":"Hằng số trong PHP","description":"Hằng số trong PHP","date":null,"path":"php - constant"},
{"category":"php","title":"cURL","description":"download","date":null,"path":"php - curl"},
{"category":"php","title":"","description":"","date":null,"path":"php - datetime"},
{"category":"php","title":"Debug code PHP","description":"Debug code PHP","date":null,"path":"php - debug"},
{"category":"php","title":"","description":"","date":null,"path":"php - dompdf"},
{"category":"php","title":"Thao tác file Excel với PHP","description":"Thao tác file Excel với PHP","date":null,"path":"php - excel"},
{"category":"php","title":"Lỗi xuất báo cáo Excel với PHP","description":"invalid xml characters","date":null,"path":"php - excel error"},
{"category":"php","title":"Xử lý Exception trong PHP","description":"Xử lý Exception trong PHP","date":null,"path":"php - exception"},
{"category":"php","title":"Thực hiện các lệnh hệ thống với PHP","description":"exec, system, rar, 7z","date":null,"path":"php - execute external command"},
{"category":"php","title":"PHP CLI","description":"PHP CLI","date":null,"path":"php - execute from cli"},
{"category":"php","title":"PHP extension","description":"phpize","date":null,"path":"php - extension"},
{"category":"php","title":"Tạo dữ liệu với Faker","description":"Tạo dữ liệu với Faker","date":null,"path":"php - faker"},
{"category":"php","title":"Xử lý dữ liệu trên file trong PHP","description":"read, write","date":null,"path":"php - file"},
{"category":"php","title":"Lập trình PHP","description":"PHP Get Started","date":null,"path":"php - get started"},
{"category":"php","title":"Sử dụng Guzzle để gọi API","description":"PHP Guzzle","date":null,"path":"php - guzzle"},
{"category":"php","title":"Heredoc và nowdoc","description":"Heredoc và nowdoc","date":null,"path":"php - heredoc and nowdoc"},
{"category":"php","title":"HTML Parser","description":"DOMDocument, purify, sanitize","date":null,"path":"php - html parser"},
{"category":"php","title":"HTML purifier","description":"sanitize, xss","date":null,"path":"php - html purifier"},
{"category":"php","title":"","description":"","date":null,"path":"php - ixudra curl"},
{"category":"php","title":"Xử lý JSON trong PHP","description":"Xử lý JSON trong PHP","date":null,"path":"php - json"},
{"category":"php","title":"Đăng nhập LDAP với PHP","description":"ldap, php, adldap2, laravel","date":null,"path":"php - ldap"},
{"category":"php","title":"","description":"","date":null,"path":"php - merge images"},
{"category":"php","title":"Mock API","description":"Giả lập dữ liệu từ server, REST, socket server","date":null,"path":"php - mock api"},
{"category":"php","title":"Cài đặt ứng dụng PHP thuần sử dụng MVC và OOP","description":"Cài đặt ứng dụng PHP thuần sử dụng MVC và OOP","date":null,"path":"php - mvc"},
{"category":"php","title":"Truy cập MySQL với PHP","description":"pdo, mysqli","date":null,"path":"php - mysql"},
{"category":"php","title":"Những cái mới trong PHP 8","description":"php8","date":null,"path":"php - new features php8"},
{"category":"php","title":"Lập trình hướng đối tượng với PHP","description":"Lập trình hướng đối tượng với PHP","date":null,"path":"php - oop"},
{"category":"php","title":"Kiểm tra loại hệ điều hành","description":"Kiểm tra loại hệ điều hành","date":null,"path":"php - os"},
{"category":"php","title":"","description":"","date":null,"path":"php - password hash"},
{"category":"php","title":"PHAR file format","description":"PHAR file format","date":null,"path":"php - phar file format"},
{"category":"php","title":"Sử dụng PHPExcel","description":"Sử dụng PHPExcel","date":null,"path":"php - phpexcel"},
{"category":"php","title":"","description":"","date":null,"path":"php - phpmailer"},
{"category":"php","title":"PHP Unit Test","description":"PHP Unit Test","date":null,"path":"php - phpunit"},
{"category":"php","title":"Các chuẩn PHP khuyên dùng","description":"PSR","date":null,"path":"php - psr"},
{"category":"php","title":"Sử dụng PHP thuần với Laravel Mix","description":"Không sử dụng Laravel","date":null,"path":"php - pure php and mix"},
{"category":"php","title":"Tạo raw HTTP request","description":"socket","date":null,"path":"php - raw http request"},
{"category":"php","title":"Đọc mail với PHP","description":"imap, pop3","date":null,"path":"php - read mail"},
{"category":"php","title":"Biểu thức chính quy trong PHP","description":"regex, preg_match","date":null,"path":"php - regular expression"},
{"category":"php","title":"Rename","description":"Đổi tên file hàng loạt, check special characters","date":null,"path":"php - rename"},
{"category":"php","title":"Cách tạo router - routing - PHP","description":"Cách tạo router - routing - PHP","date":null,"path":"php - route"},
{"category":"php","title":"","description":"","date":null,"path":"php - soap client"},
{"category":"php","title":"","description":"","date":null,"path":"php - sprintf function"},
{"category":"php","title":"Sử dụng SQLite với PHP","description":"sqlite","date":null,"path":"php - sqlite"},
{"category":"php","title":"Các hàm xử lý xâu trong PHP","description":"Các hàm xử lý xâu trong PHP","date":null,"path":"php - string functions"},
{"category":"php","title":"","description":"","date":null,"path":"php - swiftmailer"},
{"category":"php","title":"Cách tạo template engine kế thừa trong PHP","description":"Cách tạo template engine kế thừa trong PHP","date":null,"path":"php - template engine"},
{"category":"php","title":"Top 100 hàm PHP","description":"Top 100 hàm PHP","date":null,"path":"php - top 100 functions"},
{"category":"php","title":"Trait trong php","description":"Trait trong php","date":null,"path":"php - trait"},
{"category":"php","title":"Biến trong PHP","description":"Biến trong PHP","date":null,"path":"php - variable"},
{"category":"php","title":"","description":"","date":null,"path":"php - variable reference"},
{"category":"php","title":"PHP watermark","description":"PHP watermark","date":null,"path":"php - watermark"},
{"category":"php","title":"Thao tác với ZIP file bằng PHP","description":"zip, rar, extract, compress, docx","date":null,"path":"php - zip"},
{"category":"project","title":"AFF 2018 Thailand","description":"AFF 2018 Thailand","date":null,"path":"project - aff cup 2018"},
{"category":"project","title":"Audio truyện","description":"playlist, Tam quốc diễn nghĩa","date":null,"path":"project - audio book"},
{"category":"project","title":"JS Calculator","description":"JS Calculator","date":null,"path":"project - calculator"},
{"category":"project","title":"Lớp Toán khóa 2002-2005 trường THPT Chuyên Hưng Yên","description":"Lớp Toán khóa 2002-2005 trường THPT Chuyên Hưng Yên","date":null,"path":"project - classmates"},
{"category":"project","title":"Clean HTML","description":"Chỉ giữ những thẻ cần thiết nhất","date":null,"path":"project - clean html"},
{"category":"project","title":"Split ảnh truyện tranh","description":"Split ảnh truyện tranh","date":null,"path":"project - comic split"},
{"category":"project","title":"eComix","description":"cbz, cbr, vue module, comic viewer","date":null,"path":"project - comic viewer"},
{"category":"project","title":"Quản lý truyện tranh","description":"comics manager","date":null,"path":"project - comics manager"},
{"category":"project","title":"Common validation","description":"Validate thời gian thực","date":"2020-02-24 22:07:00","path":"project - common validation"},
{"category":"project","title":"CTTD","description":"CTTD","date":null,"path":"project - cttd"},
{"category":"project","title":"Datatable","description":"sort, search, pagination, bootstrap, table, fixed header, fixed column","date":"2020-02-24 22:35:00","path":"project - datatable"},
{"category":"project","title":"","description":"","date":null,"path":"project - diff"},
{"category":"project","title":"","description":"","date":null,"path":"project - disable open new ad tab"},
{"category":"project","title":"Đọc truyện đêm khuya","description":"Đọc truyện đêm khuya","date":null,"path":"project - doc truyen"},
{"category":"project","title":"DownGit","description":"Download GitHub folder, zip","date":null,"path":"project - download github folder"},
{"category":"project","title":"Những từ tiếng Anh thông dụng","description":"Học tiếng Anh với hình ảnh và âm thanh","date":null,"path":"project - english common words"},
{"category":"project","title":"Spritz Speed Reading V2","description":"Spritz Speed Reading V2","date":null,"path":"project - fast read (spritz-speed-reading-v2)"},
{"category":"project","title":"Đọc nhanh","description":"Đọc nhanh từng từ của một đoạn văn bản","date":null,"path":"project - fast read 1"},
{"category":"project","title":"Format CSS","description":"Format CSS","date":null,"path":"project - format css"},
{"category":"project","title":"Các framework và thư viện frontend hay dùng","description":"cdn, zip","date":"2020-02-24 18:28:00","path":"project - frontend frameworks and libraries"},
{"category":"project","title":"Get links","description":"Lấy các link (ảnh, video) để download. Lấy nội dung, thông tin của ảnh.","date":null,"path":"project - get links"},
{"category":"project","title":"Trang chủ","description":"motorbike oil alert, calendar, water, electricity, bill warning","date":null,"path":"project - homepage"},
{"category":"project","title":"Lịch của tôi","description":"lunar calendar, Progressive Web App, pwa, lichcuatoi.github.io, offline, service worker","date":null,"path":"project - lich cua toi"},
{"category":"project","title":"","description":"","date":null,"path":"project - lien hoan hoa"},
{"category":"project","title":"","description":"","date":null,"path":"project - manga rock image decoder"},
{"category":"project","title":"View Position","description":"View Position","date":null,"path":"project - map"},
{"category":"project","title":"Markdown preview","description":"Markdown preview","date":null,"path":"project - markdown preview"},
{"category":"project","title":"","description":"","date":null,"path":"project - mdm"},
{"category":"project","title":"Media player","description":"audio, video, subtitle, karaoke","date":null,"path":"project - media player"},
{"category":"project","title":"精選","description":"a collection of songs that I love, also shows how to sync lyric with HTML5 audio tag","date":null,"path":"project - media player wayou selected"},
{"category":"project","title":"Money Manager","description":"Money Manager","date":null,"path":"project - money manager"},
{"category":"project","title":"","description":"","date":null,"path":"project - movie api"},
{"category":"project","title":"My Family","description":"genealogy, tree","date":null,"path":"project - my family"},
{"category":"project","title":"","description":"","date":null,"path":"project - my notes"},
{"category":"project","title":"Noti","description":"Thay thế alert và confirm","date":"2020-02-24 22:06:00","path":"project - noti"},
{"category":"project","title":"Page viewer","description":"Đọc từng trang","date":null,"path":"project - page viewer"},
{"category":"project","title":"Pagi","description":"A pagination library written by myself","date":"2020-04-16 18:21:00","path":"project - pagi"},
{"category":"project","title":"Quản lý bài viết","description":"jsdom, html parser","date":"2020-01-01 15:56:00","path":"project - post management"},
{"category":"project","title":"Puzzle","description":"A puzzle game","date":null,"path":"project - puzzle"},
{"category":"project","title":"","description":"","date":null,"path":"project - realtime corona"},
{"category":"project","title":"Sherlock Holmes collection","description":"Sherlock Holmes collection","date":null,"path":"project - sherlock holmes"},
{"category":"project","title":"Short funny stories","description":"Short stories","date":null,"path":"project - short"},
{"category":"project","title":"Đồng bộ lại phụ đề","description":"Chỉnh lại thời gian của phụ đề cho khớp, Java","date":null,"path":"project - subtitle"},
{"category":"project","title":"Playlist audio truyện cổ tích","description":"Playlist audio truyện cổ tích","date":null,"path":"project - truyen co tich"},
{"category":"project","title":"Đọc truyện audio bằng tổng hợp tiếng nói","description":"tts, guzzle, php","date":null,"path":"project - tts audio book"},
{"category":"project","title":"Upload file","description":"Upload từ iPad sang máy tính, download từ máy tính sang iPad","date":null,"path":"project - upload file"},
{"category":"project","title":"Playlist video truyện cổ tích Việt Nam","description":"Playlist video cổ tích Việt Nam","date":null,"path":"project - video playlist"},
{"category":"project","title":"Đơn vị hành chính","description":"Dữ liệu tỉnh, huyện, xã của Việt Nam","date":null,"path":"project - vietnamese divisions"},
{"category":"project","title":"Vòng quay may mắn","description":"Vòng quay may mắn","date":null,"path":"project - vong quay may man"},
{"category":"project","title":"Dự báo thời tiết","description":"","date":null,"path":"project - weather app"},
{"category":"project","title":"World Cup 2018","description":"World Cup 2018","date":null,"path":"project - world cup 2018"},
{"category":"python","title":"","description":"","date":null,"path":"python - get started"},
{"category":"react","title":"Create React App","description":"Tool tạo ứng dụng React","date":null,"path":"react - create react app"},
{"category":"react","title":"Học React","description":"Học React","date":null,"path":"react - get started"},
{"category":"react","title":"React hook","description":"React hook","date":null,"path":"react - hooks"},
{"category":"react","title":"Redux","description":"Redux","date":null,"path":"react - redux"},
{"category":"react","title":"Redux saga","description":"Redux saga","date":null,"path":"react - redux saga"},
{"category":"react","title":"React router","description":"React router","date":null,"path":"react - router"},
{"category":"react","title":"React tic-tac-toe","description":"Ví dụ bắt đầu","date":null,"path":"react - tic-tac-toe game"},
{"category":"react","title":"React Slider w/ Hover Effect","description":"React without JSX","date":null,"path":"react - without jsx"},
{"category":"redis","title":"Redis","description":"Redis","date":null,"path":"redis - get started"},
{"category":"redis","title":"Cài đặt Redis","description":"Cài đặt Redis","date":"2020-02-21 23:20:00","path":"redis - installation"},
{"category":"story","title":"Các nhân vật trong truyện Dragon Ball đã giết bao nhiêu người","description":"dragon ball","date":null,"path":"story - all kills of dragon ball characters"},
{"category":"story","title":"Màn ngược dòng không tưởng đưa Barca vào tứ kết","description":"football","date":null,"path":"story - barca"},
{"category":"story","title":"Chú chó con","description":"a story about a dog","date":null,"path":"story - chu cho con"},
{"category":"story","title":"Core Values","description":"Core Values","date":null,"path":"story - core values"},
{"category":"story","title":"Chuyện cổ tích có thật về người thầy hiệu trưởng - “cha nuôi” của cậu bé tí hon 10 tuổi nặng 3,9 kg","description":"Đặng Văn Cương, Đinh Văn K'Rể, inspiration","date":null,"path":"story - dinh van kre, dang van cuong"},
{"category":"story","title":"Đừng học tiếng Anh, hãy sử dụng","description":"learn, study, use","date":"2020-01-01 11:50:00","path":"story - dont learn english, use it"},
{"category":"story","title":"Dresses of different nations","description":"Dresses of different nations","date":null,"path":"story - dresses of different nations"},
{"category":"story","title":"Ghen tỵ","description":"Ghen tỵ","date":null,"path":"story - envy"},
{"category":"story","title":"First time in my life","description":"The first time","date":null,"path":"story - first time in my life"},
{"category":"story","title":"Football","description":"Football","date":null,"path":"story - football and life"},
{"category":"story","title":"Bảng chỉ số chiều cao, cân nặng của trẻ","description":"Bảng chỉ số chiều cao, cân nặng của trẻ","date":null,"path":"story - height and weight of child"},
{"category":"story","title":"Những hình ảnh minh họa 'bất hủ' của sách Tập đọc xưa","description":"Những hình ảnh minh họa 'bất hủ' của sách Tập đọc xưa","date":null,"path":"story - hinh anh minh hoa sach tap doc xua"},
{"category":"story","title":"Hoài niệm cùng những món \"đồ cổ\" gắn liền với thế hệ 8x","description":"Hoài niệm cùng những món ","date":null,"path":"story - hoai niem cung nhung mon do co gan lien voi the he 8x"},
{"category":"story","title":"Xây nhà","description":"House construction","date":null,"path":"story - house construction"},
{"category":"story","title":"Các ý tưởng của tôi","description":"My ideas","date":null,"path":"story - ideas"},
{"category":"story","title":"Journey to the West","description":"Journey to the West","date":null,"path":"story - journey to the west"},
{"category":"story","title":"Không có tên","description":"Truyện ngắn hay về tình mẫu tử của Nguyễn Thu Hằng","date":null,"path":"story - khong co ten (nguyen thu hang)"},
{"category":"story","title":"Lịch tiêm chủng","description":"Lịch tiêm chủng cho con","date":null,"path":"story - lich tiem chung"},
{"category":"story","title":"Life as a Sales Engineer","description":"Life as a Sales Engineer","date":null,"path":"story - life as a sales engineer"},
{"category":"story","title":"My Idols","description":"My Idols","date":null,"path":"story - my idols"},
{"category":"story","title":"Kế hoạch cho tương lai","description":"Plan the future","date":null,"path":"story - my plan"},
{"category":"story","title":"Nutritious Food","description":"Nutritious Food","date":null,"path":"story - nutrious food"},
{"category":"story","title":"","description":"","date":null,"path":"story - personal names"},
{"category":"story","title":"Cách phân biệt các điểm du lịch tâm linh","description":"Phân biệt đình, chùa, miếu, am,...","date":null,"path":"story - phan biet dinh chua"},
{"category":"story","title":"Truyện Q.E.D","description":"Danh sách tập, vụ án, kiến thức khoa học","date":null,"path":"story - q.e.d"},
{"category":"story","title":"Lời hay ý đẹp","description":"Lời hay ý đẹp","date":null,"path":"story - quotes"},
{"category":"story","title":"Superior Spider-Man","description":"Superior Spider-Man","date":null,"path":"story - superior spider-man"},
{"category":"story","title":"Giảm trừ gia cảnh","description":"Giảm trừ gia cảnh","date":null,"path":"story - tax deduction"},
{"category":"story","title":"Tây du ký","description":"Tây du ký","date":null,"path":"story - tay du ky"},
{"category":"story","title":"The Story of Life","description":"A very good article","date":null,"path":"story - the story of life"},
{"category":"story","title":"Người nặng lòng với truyện tranh Việt","description":"Người nặng lòng với truyện tranh Việt","date":null,"path":"story - truyen tranh viet nam"},
{"category":"story","title":"Truyện tranh","description":"Truyện tranh","date":null,"path":"story - truyen tranh xua"},
{"category":"story","title":"Hướng dẫn rửa bát","description":"Hướng dẫn rửa bát","date":null,"path":"story - washing dish"},
{"category":"story","title":"Websites","description":"Danh sách các trang web hay vào","date":null,"path":"story - websites"},
{"category":"ui","title":"Auto Grow","description":"Auto Grow","date":null,"path":"ui - auto grow"},
{"category":"ui","title":"Auto-complete inline","description":"Auto-complete inline","date":null,"path":"ui - auto-complete inline"},
{"category":"ui","title":"Book cover","description":"Book cover","date":null,"path":"ui - book cover"},
{"category":"ui","title":"Bubble Animation","description":"Bubble Animation","date":null,"path":"ui - bubble animation"},
{"category":"ui","title":"Calendar","description":"","date":null,"path":"ui - calendar"},
{"category":"ui","title":"Card grid","description":"Pokedex","date":null,"path":"ui - card grid"},
{"category":"ui","title":"Bảng chữ cái","description":"Alphabet","date":null,"path":"ui - card grid (alphabet)"},
{"category":"ui","title":"Carousel","description":"carousel, water margin, thủy hử, 108 vị anh hùng Lương Sơn Bạc, 108 heroes","date":"2020-06-22 21:15:00","path":"ui - carousel"},
{"category":"ui","title":"Change Image","description":"Change Image","date":null,"path":"ui - change image onhover"},
{"category":"ui","title":"Street Fighter - Character Selection","description":"Built by Vue and Bulma","date":null,"path":"ui - character selection"},
{"category":"ui","title":"Chiến tranh biên giới Việt - Trung","description":"Chiến tranh biên giới Việt - Trung","date":null,"path":"ui - chien tranh bien gioi viet trung"},
{"category":"ui","title":"Clearable","description":"Clear input content","date":null,"path":"ui - clearable"},
{"category":"ui","title":"Step connector","description":"progress circles","date":null,"path":"ui - connector"},
{"category":"ui","title":"","description":"","date":null,"path":"ui - cover board"},
{"category":"ui","title":"Tùy chỉnh style cho thanh scrollbar","description":"Tùy chỉnh style cho thanh scrollbar","date":null,"path":"ui - customize scrollbar"},
{"category":"ui","title":"Date range picker","description":"Chọn khoảng ngày. Có những khoảng ngày định nghĩa trước cho tiện.","date":null,"path":"ui - date range picker"},
{"category":"ui","title":"jQuery UI datepicker","description":"jQuery UI datepicker","date":null,"path":"ui - datepicker"},
{"category":"ui","title":"Datepicker Dialog","description":"Cho phép chọn ngày, khoảng ngày, tuần, tháng, mùa, năm","date":null,"path":"ui - datepicker dialog"},
{"category":"ui","title":"Phần tử details","description":"details, summary, accordion, collapse, expand, fieldset, legend, heading","date":null,"path":"ui - details"},
{"category":"ui","title":"Diagonal background","description":"chéo, transform skew, gradient background, css shape triangle","date":null,"path":"ui - diagonal"},
{"category":"ui","title":"","description":"","date":null,"path":"ui - dock"},
{"category":"ui","title":"Drag position","description":"Di chuyển vị trí phần tử absolute","date":null,"path":"ui - drag position"},
{"category":"ui","title":"Dragon Ball","description":"Dragon Ball","date":null,"path":"ui - dragon ball 42 volumes"},
{"category":"ui","title":"","description":"","date":null,"path":"ui - dropdown"},
{"category":"ui","title":"Elapsing Time","description":"Elapsing Time","date":null,"path":"ui - elapsing time"},
{"category":"ui","title":"","description":"","date":null,"path":"ui - emoticon"},
{"category":"ui","title":"Fit Text","description":"Fit Text with CSS Variables","date":null,"path":"ui - fit text with css variables"},
{"category":"ui","title":"Fit to width","description":"Fit to width","date":null,"path":"ui - fit to width"},
{"category":"ui","title":"Giao diện game","description":"Có animation, style của game","date":null,"path":"ui - flame"},
{"category":"ui","title":"Floating elements mini snippet","description":"Floating elements mini snippet","date":null,"path":"ui - floating elements"},
{"category":"ui","title":"Font Awesome","description":"Font Awesome","date":null,"path":"ui - font awesome"},
{"category":"ui","title":"Football icons","description":"Biểu tượng của các đội tuyển quốc gia, các câu lạc bộ","date":null,"path":"ui - football icons"},
{"category":"ui","title":"Football Match","description":"Football Match","date":null,"path":"ui - football match"},
{"category":"ui","title":"Fullscreen video background","description":"Fullscreen video background","date":null,"path":"ui - fullscreen video background"},
{"category":"ui","title":"Gallery","description":"Image gallery","date":null,"path":"ui - gallery"},
{"category":"ui","title":"Biểu đồ Gauge","description":"Biểu đồ Gauge","date":null,"path":"ui - gauge chart"},
{"category":"ui","title":"Generate Icon","description":"Generate Icon","date":null,"path":"ui - generate icon"},
{"category":"ui","title":"Globe","description":"Globe","date":null,"path":"ui - globe"},
{"category":"ui","title":"","description":"","date":null,"path":"ui - glossy effect"},
{"category":"ui","title":"Gradient","description":"Gradient","date":null,"path":"ui - gradient"},
{"category":"ui","title":"Hamburger menu icon","description":"animation đóng mở","date":null,"path":"ui - hamburger menu icon"},
{"category":"ui","title":"","description":"","date":null,"path":"ui - hide text too long"},
{"category":"ui","title":"Highlight các thay đổi","description":"Highlight các thay đổi","date":null,"path":"ui - highlight changes"},
{"category":"ui","title":"Horizontal Scroll","description":"Horizontal Scroll","date":null,"path":"ui - horizontal scroll"},
{"category":"ui","title":"Sử dụng icon trên web","description":"Sử dụng icon trên web","date":null,"path":"ui - icon"},
{"category":"ui","title":"So sánh 2 hình ảnh","description":"So sánh 2 hình ảnh","date":null,"path":"ui - image comparison slider"},
{"category":"ui","title":"Image fading transition","description":"Image fading transition","date":null,"path":"ui - image fading transition"},
{"category":"ui","title":"Kính lúp","description":"Image magnifier glass","date":null,"path":"ui - image magnifier glass"},
{"category":"ui","title":"","description":"","date":null,"path":"ui - image map"},
{"category":"ui","title":"Kính lúp","description":"loupe, magnifier, image zoom","date":null,"path":"ui - image zoom"},
{"category":"ui","title":"Inline Edit","description":"Inline Edit","date":null,"path":"ui - inline edit"},
{"category":"ui","title":"Justice League Action","description":"ffmpeg, python subprocess, thumbnail","date":null,"path":"ui - justice league action"},
{"category":"ui","title":"Karaoke","description":"Karaoke","date":null,"path":"ui - karaoke"},
{"category":"ui","title":"Ken Burns Effect","description":"Ken Burns Effect","date":null,"path":"ui - ken burns effect"},
{"category":"ui","title":"","description":"","date":null,"path":"ui - layout"},
{"category":"ui","title":"Bottom footer","description":"Để footer ở cuối trang. Có thể áp dụng để trang hiển thị full chiều cao màn hình.","date":null,"path":"ui - layout bottom footer"},
{"category":"ui","title":"Full-screen layout","description":"Full-screen layout","date":null,"path":"ui - layout fullscreen"},
{"category":"ui","title":"Light Loader","description":"Light Loader","date":null,"path":"ui - light loader"},
{"category":"ui","title":"Line Awesome","description":"Bộ icon dùng trên web","date":null,"path":"ui - line awesome"},
{"category":"ui","title":"Loader","description":"Loader","date":null,"path":"ui - loader"},
{"category":"ui","title":"Đếm ngược tết","description":"Đếm ngược tết","date":null,"path":"ui - lunar new year"},
{"category":"ui","title":"Intro to amMap","description":"Intro to amMap","date":null,"path":"ui - map ammap"},
{"category":"ui","title":"","description":"","date":null,"path":"ui - map echarts"},
{"category":"ui","title":"Preloader --3","description":"Preloader --3","date":null,"path":"ui - marquee"},
{"category":"ui","title":"Masonry","description":"masonry, column, flex","date":null,"path":"ui - masonry"},
{"category":"ui","title":"Bootstrap Maxlength","description":"Bootstrap Maxlength","date":null,"path":"ui - maxlength indicator"},
{"category":"ui","title":"Menu","description":"Menu","date":null,"path":"ui - menu"},
{"category":"ui","title":"","description":"","date":null,"path":"ui - metro card"},
{"category":"ui","title":"Mini-Preview link","description":"Hover trên link sẽ hiển thị popup nhỏ chứa screen của target","date":null,"path":"ui - mini preview links"},
{"category":"ui","title":"Chọn tháng","description":"Month picker","date":null,"path":"ui - month picker"},
{"category":"ui","title":"Hiệu ứng parallax nhiều tầng với ảnh và văn bản","description":"Hiệu ứng parallax nhiều tầng với ảnh và văn bản","date":null,"path":"ui - multi layered parallax"},
{"category":"ui","title":"Neon text-shadow effect","description":"Neon text-shadow effect","date":null,"path":"ui - neon text-shadow effect"},
{"category":"ui","title":"Nestable","description":"Kéo thả danh sách dạng cây, tree","date":null,"path":"ui - nestable"},
{"category":"ui","title":"One Piece chapters","description":"One Piece chapters","date":null,"path":"ui - one piece chapters"},
{"category":"ui","title":"","description":"","date":null,"path":"ui - overlay"},
{"category":"ui","title":"Page split","description":"Tách các thành phần của trang web thành các trang có kích thước cố định","date":null,"path":"ui - page split"},
{"category":"ui","title":"pagemap","description":"pagemap","date":null,"path":"ui - pagemap"},
{"category":"ui","title":"Paper","description":"Paper","date":null,"path":"ui - paper"},
{"category":"ui","title":"Hoạt họa parallax","description":"Animated parallax banner","date":null,"path":"ui - parallax animation"},
{"category":"ui","title":"Parallax background","description":"Parallax background","date":null,"path":"ui - parallax background"},
{"category":"ui","title":"Các thành phần parallax","description":"Parallax elements, porfolio page","date":null,"path":"ui - parallax elements"},
{"category":"ui","title":"Pure CSS Particle Animation","description":"Pure CSS Particle Animation","date":null,"path":"ui - particle animation"},
{"category":"ui","title":"","description":"","date":null,"path":"ui - pie chart"},
{"category":"ui","title":"Pin một phần tử","description":"Pin một phần tử","date":null,"path":"ui - pin element"},
{"category":"ui","title":"","description":"","date":null,"path":"ui - progress bar"},
{"category":"ui","title":"Radar chart","description":"Thống kê chỉ số của các vận động viên","date":null,"path":"ui - radar chart"},
{"category":"ui","title":"Hiển thị ngẫu nhiên ảnh","description":"random image, thecatapi, unsplash, giphy, beautiful gravure girl, chú thoòng, old master q","date":null,"path":"ui - random image"},
{"category":"ui","title":"Reflection","description":"Phản chiếu, bóng loáng","date":null,"path":"ui - reflection"},
{"category":"ui","title":"Refracted Floating Text Effect","description":"Refracted Floating Text Effect","date":null,"path":"ui - refracted floating text effect"},
{"category":"ui","title":"Resizable div","description":"Resizable div","date":null,"path":"ui - resizable div"},
{"category":"ui","title":"Responsive Design","description":"Responsive Design","date":null,"path":"ui - responsive design"},
{"category":"ui","title":"Ribbon","description":"Ribbon","date":null,"path":"ui - ribbon"},
{"category":"ui","title":"Row and Column Highlighting with CSS Only","description":"Row and Column Highlighting with CSS Only","date":null,"path":"ui - row and column highlighting"},
{"category":"ui","title":"Hiện thanh scrollbar khi hover","description":"Hiện thanh scrollbar khi hover","date":null,"path":"ui - scroll hover"},
{"category":"ui","title":"Tùy chỉnh scrollbar","description":"Tùy chỉnh Scrollbar","date":null,"path":"ui - scrollbar"},
{"category":"ui","title":"","description":"","date":null,"path":"ui - search box"},
{"category":"ui","title":"Selectable","description":"Selectable","date":null,"path":"ui - selectable"},
{"category":"ui","title":"The Shapes of CSS","description":"The Shapes of CSS","date":null,"path":"ui - shapes with css"},
{"category":"ui","title":"Shuffle Animation","description":"Shuffle Animation","date":null,"path":"ui - shuffle animation"},
{"category":"ui","title":"Sidebar navigation","description":"Sidebar navigation","date":null,"path":"ui - sidebar"},
{"category":"ui","title":"Slide show animation","description":"Wedding photos of Huyên and Dương","date":null,"path":"ui - slide show"},
{"category":"ui","title":"Sparkle animation","description":"Heart animation - click it!","date":null,"path":"ui - sparkle animation"},
{"category":"ui","title":"","description":"","date":null,"path":"ui - speed line"},
{"category":"ui","title":"Tách một ảnh thành nhiều ảnh nhỏ","description":"canvas","date":null,"path":"ui - split image"},
{"category":"ui","title":"Dragbar","description":"Thay đổi kích thước","date":null,"path":"ui - split panels resizable"},
{"category":"ui","title":"","description":"","date":null,"path":"ui - spoiler"},
{"category":"ui","title":"","description":"","date":null,"path":"ui - spotlight"},
{"category":"ui","title":"","description":"","date":null,"path":"ui - sticky"},
{"category":"ui","title":"Sticky headers with IntersectionObserver","description":"Sticky headers with IntersectionObserver","date":null,"path":"ui - sticky header with intersectionobserver"},
{"category":"ui","title":"Sticky sections (pure CSS)","description":"Sticky sections (pure CSS)","date":null,"path":"ui - sticky sections pure css"},
{"category":"ui","title":"Sunburst eCharts","description":"Sunburst eCharts","date":null,"path":"ui - sunburst chart"},
{"category":"ui","title":"Swipe","description":"Swipe","date":null,"path":"ui - swipe"},
{"category":"ui","title":"Tab","description":"Tab","date":null,"path":"ui - tab"},
{"category":"ui","title":"Tạo tab với sliding phía dưới","description":"Tạo tab với sliding phía dưới","date":null,"path":"ui - tabs with sliding underline"},
{"category":"ui","title":"","description":"","date":null,"path":"ui - text"},
{"category":"ui","title":"Ẩn hiện navigator khi scroll","description":"Toggle navigator when scrolling","date":null,"path":"ui - toggle nav when scroll"},
{"category":"ui","title":"Tooltip","description":"tooltip","date":null,"path":"ui - tooltip"},
{"category":"ui","title":"","description":"","date":null,"path":"ui - tree diagram"},
{"category":"ui","title":"","description":"","date":null,"path":"ui - tree drawing"},
{"category":"ui","title":"Tree grid","description":"Bảng dữ liệu dạng cây","date":null,"path":"ui - tree grid"},
{"category":"ui","title":"User rating","description":"User rating","date":null,"path":"ui - user rating"},
{"category":"ui","title":"Ảnh cưới của vợ chồng tôi","description":"lazy load, prefetch, fancybox, lighbox","date":null,"path":"ui - wedding photos"},
{"category":"ui","title":"Chọn tuần","description":"Week picker","date":null,"path":"ui - week picker"},
{"category":"ui","title":"Word cloud","description":"Highcharts, jqcloud2, tag, từ khóa nổi bật","date":null,"path":"ui - word cloud"},
{"category":"vue","title":"Component trong Vue","description":"v-model","date":null,"path":"vue - component"},
{"category":"vue","title":"Custom event trong component","description":"v-model, sync","date":null,"path":"vue - component custom event"},
{"category":"vue","title":"Slot trong Vue","description":"slot","date":null,"path":"vue - component slot"},
{"category":"vue","title":"Vue form validation","description":"Validate với Vue","date":null,"path":"vue - form validation"},
{"category":"vue","title":"Vue Fullpage Scroll","description":"Vue Fullpage Scroll","date":null,"path":"vue - fullpage scroll"},
{"category":"vue","title":"Bắt đầu học Vue","description":"Bắt đầu học Vue","date":null,"path":"vue - get started"},
{"category":"vue","title":"Sử dụng thư viện Linkify với Vue","description":"Sử dụng thư viện Linkify với Vue","date":null,"path":"vue - linkify"},
{"category":"vue","title":"Tạo SPA với Vue","description":"Single Page Application","date":null,"path":"vue - spa"},
{"category":"vue","title":"Transition cho enter/leave & danh sách","description":"","date":null,"path":"vue - transitions"},
{"category":"vue","title":"Unit test với Vue","description":"Unit test với Vue","date":null,"path":"vue - unit test"},
{"category":"vue","title":"VeeValidate","description":"VeeValidate","date":null,"path":"vue - veevalidate"},
{"category":"vue","title":"Vue tags input","description":"Danh sách thẻ","date":null,"path":"vue - vue tags input"},
{"category":"webext","title":"Batch downloader","description":"Tiện ích download file hàng loạt","date":null,"path":"webext - batch downloader"},
{"category":"webext","title":"Web Extension Bookmarks","description":"Web Extension Bookmarks","date":null,"path":"webext - bookmarks api"},
{"category":"webext","title":"Browse my repo","description":"Change URL between my website and GitHub","date":null,"path":"webext - browse my repo"},
{"category":"webext","title":"","description":"","date":null,"path":"webext - browser history"},
{"category":"webext","title":"Cloud downloader","description":"Download từ các trang như usercloud, zippyshare, fshare, mega","date":null,"path":"webext - cloud downloader"},
{"category":"webext","title":"Cốc Cốc Savior","description":"Bắt link và download các video, audio","date":null,"path":"webext - coc coc savior"},
{"category":"webext","title":"CORS unblock","description":"Cho phép gọi AJAX đến domain khác","date":null,"path":"webext - cors unblock"},
{"category":"webext","title":"Lấy source code của một extension","description":"Lấy source code của một extension","date":null,"path":"webext - get source code"},
{"category":"webext","title":"Web Extension","description":"Web Extension","date":null,"path":"webext - get started"},
{"category":"webext","title":"","description":"","date":null,"path":"webext - pin video"},
{"category":"webext","title":"Net Filter","description":"Net Filter","date":null,"path":"webext - safenet addon"},
{"category":"webext","title":"Set referer","description":"Set referer","date":null,"path":"webext - set referer"},
{"category":"webext","title":"","description":"","date":null,"path":"webext - steal this page"},
{"category":"webext","title":"Đồng bộ bookmark","description":"Đẩy dữ liệu bookmark từ máy công ty lên cloud để máy ở nhà cũng xem được","date":null,"path":"webext - sync bookmarks"},
{"category":"webext","title":"timeStats - Time statistics","description":"timeStats - Time statistics","date":null,"path":"webext - timestats"},
{"category":"webext","title":"","description":"","date":null,"path":"webext - web cleaner"},
{"category":"webext","title":"","description":"","date":null,"path":"webext - youtube ads remover"},
{"category":"webext","title":"Tiện ích download subtitle từ YouTube","description":"youtube, subtitle, download, closed caption","date":null,"path":"webext - youtube subtitle downloader"},
{"category":"webext","title":"","description":"","date":null,"path":"webext - youtube video downloader"},
{"category":"webrtc","title":"Truyền file","description":"Transfer a file","date":null,"path":"webrtc - file transfer"},
{"category":"webrtc","title":"WebRTC","description":"WebRTC","date":null,"path":"webrtc - get started"},
{"category":"webrtc","title":"Channel đơn giản","description":"WebRTC: Simple RTCDataChannel sample","date":null,"path":"webrtc - simple datachannel"}
];
