const NATIONALS = [
    'argentina.svg',
    'austria.svg',
    'belgium.svg',
    'bulgaria.svg',
    'canada.svg',
    'colombia.svg',
    'croatia.svg',
    'czech.svg',
    'denmark.svg',
    'england.svg',
    'france.svg',
    'germany.svg',
    'greece.svg',
    'hong kong.svg',
    'iceland.svg',
    'italy.svg',
    'jamaica.svg',
    'japan.svg',
    'korea.svg',
    'malaysia.svg',
    'mexico.svg',
    'montenegro.svg',
    'netherlands.svg',
    'norway.svg',
    'panama.svg',
    'paraguay.svg',
    'poland.svg',
    'portugal.svg',
    'romania.svg',
    'russia.svg',
    'scotland.svg',
    'serbia.svg',
    'south africa.svg',
    'spain.svg',
    'sweden.svg',
    'switzerland.svg',
    'tunisia.svg',
    'turkey.svg',
    'ukraine.svg',
    'united states.svg',
    'wales.svg'
];

const CLUBS = [
    'ac milan.svg',
    'ajax amsterdam.svg',
    'arsenal.svg',
    'as roma.svg',
    'aston villa.svg',
    'atalanta.svg',
    'athletic bilbao.svg',
    'atletico madrid.svg',
    'barcelona.svg',
    'bayer leverkusen.svg',
    'bayern munchen.svg',
    'benfica.svg',
    'borussia dortmund.svg',
    'borussia monchengladbach.svg',
    'brescia.svg',
    'bundesliga.svg',
    'chelsea.svg',
    'club brugge.svg',
    'cologne.svg',
    'deportivo alaves.svg',
    'eintracht frankfurt.svg',
    'everton.svg',
    'fiorentina.svg',
    'freiburg.svg',
    'galatasaray.svg',
    'girondins de bordeaux.svg',
    'hellas verona.svg',
    'hertha berlin.svg',
    'internazionale.svg',
    'juventus.svg',
    'la liga.svg',
    'leicester city.svg',
    'leipzig.svg',
    'lille.svg',
    'liverpool.svg',
    'lokomotiv moscow.svg',
    'mainz 05.svg',
    'manchester city.svg',
    'manchester united.svg',
    'monaco.svg',
    'napoli.svg',
    'newcastle united.svg',
    'olympiacos.svg',
    'olympique lyonnais.svg',
    'olympique marseille.svg',
    'osasuna.svg',
    'paris saint germain.svg',
    'premier league.svg',
    'real madrid.svg',
    'red bull salzburg.svg',
    'red star belgrade.svg',
    'sampdoria.svg',
    'sassuolo.svg',
    'schalke 04.svg',
    'sevilla.svg',
    'shakhtar donetsk.svg',
    'southampton.svg',
    'ss lazio.svg',
    'stade rennais.svg',
    'torino.svg',
    'tottenham hotspur.svg',
    'valencia.svg',
    'villarreal.svg',
    'watford.svg',
    'werder bremen.svg',
    'west ham.svg',
    'wolfsburg.svg',
    'wolverhampton.svg',
    'zenit saint petersburg.svg',
];
