export default [
    { name: 'js', y: 140 },
    { name: 'ui', y: 119 },
    { name: 'laravel', y: 78 },
    { name: 'php', y: 61 },
    { name: 'project', y: 49 },
    { name: 'it', y: 46 },
    { name: 'css', y: 38 },
    { name: 'linux', y: 31 },
    { name: 'git', y: 27 },
    { name: 'story', y: 21 },
    { name: 'bootstrap', y: 19 },
    { name: 'webext', y: 19 },
    { name: 'java', y: 14 },
    { name: 'mysql', y: 13 },
    { name: 'vue', y: 12 },
    { name: 'composer', y: 9 },
    { name: 'nginx', y: 8 },
    { name: 'node', y: 4 },
    { name: 'highcharts', y: 3 },
    { name: 'webrtc', y: 3 },
    { name: 'highmaps', y: 2 },
    { name: 'redis', y: 2 },
    { name: 'elasticsearch', y: 1 },
    { name: 'python', y: 1 }
];
